// Offline RDK forward kinematics and IK inspection for motion-plan JSON.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: motionplan/v1/motionplan.proto

package motionplanv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/viamrobotics/visualization/motionplan/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MotionPlanServiceName is the fully-qualified name of the MotionPlanService service.
	MotionPlanServiceName = "motionplan.v1.MotionPlanService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MotionPlanServiceGetIKSolutionsProcedure is the fully-qualified name of the MotionPlanService's
	// GetIKSolutions RPC.
	MotionPlanServiceGetIKSolutionsProcedure = "/motionplan.v1.MotionPlanService/GetIKSolutions"
)

// MotionPlanServiceClient is a client for the motionplan.v1.MotionPlanService service.
type MotionPlanServiceClient interface {
	// Per-seed IK solutions for the request's first goal, scored and constraint-checked.
	GetIKSolutions(context.Context, *connect.Request[v1.GetIKSolutionsRequest]) (*connect.Response[v1.GetIKSolutionsResponse], error)
}

// NewMotionPlanServiceClient constructs a client for the motionplan.v1.MotionPlanService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMotionPlanServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MotionPlanServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	motionPlanServiceMethods := v1.File_motionplan_v1_motionplan_proto.Services().ByName("MotionPlanService").Methods()
	return &motionPlanServiceClient{
		getIKSolutions: connect.NewClient[v1.GetIKSolutionsRequest, v1.GetIKSolutionsResponse](
			httpClient,
			baseURL+MotionPlanServiceGetIKSolutionsProcedure,
			connect.WithSchema(motionPlanServiceMethods.ByName("GetIKSolutions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// motionPlanServiceClient implements MotionPlanServiceClient.
type motionPlanServiceClient struct {
	getIKSolutions *connect.Client[v1.GetIKSolutionsRequest, v1.GetIKSolutionsResponse]
}

// GetIKSolutions calls motionplan.v1.MotionPlanService.GetIKSolutions.
func (c *motionPlanServiceClient) GetIKSolutions(ctx context.Context, req *connect.Request[v1.GetIKSolutionsRequest]) (*connect.Response[v1.GetIKSolutionsResponse], error) {
	return c.getIKSolutions.CallUnary(ctx, req)
}

// MotionPlanServiceHandler is an implementation of the motionplan.v1.MotionPlanService service.
type MotionPlanServiceHandler interface {
	// Per-seed IK solutions for the request's first goal, scored and constraint-checked.
	GetIKSolutions(context.Context, *connect.Request[v1.GetIKSolutionsRequest]) (*connect.Response[v1.GetIKSolutionsResponse], error)
}

// NewMotionPlanServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMotionPlanServiceHandler(svc MotionPlanServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	motionPlanServiceMethods := v1.File_motionplan_v1_motionplan_proto.Services().ByName("MotionPlanService").Methods()
	motionPlanServiceGetIKSolutionsHandler := connect.NewUnaryHandler(
		MotionPlanServiceGetIKSolutionsProcedure,
		svc.GetIKSolutions,
		connect.WithSchema(motionPlanServiceMethods.ByName("GetIKSolutions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/motionplan.v1.MotionPlanService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MotionPlanServiceGetIKSolutionsProcedure:
			motionPlanServiceGetIKSolutionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMotionPlanServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMotionPlanServiceHandler struct{}

func (UnimplementedMotionPlanServiceHandler) GetIKSolutions(context.Context, *connect.Request[v1.GetIKSolutionsRequest]) (*connect.Response[v1.GetIKSolutionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("motionplan.v1.MotionPlanService.GetIKSolutions is not implemented"))
}
