// Offline RDK forward kinematics and IK inspection for motion-plan JSON.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: motionplan/v1/motionplan.proto

package motionplanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIKSolutionsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PlanContent []byte                 `protobuf:"bytes,2,opt,name=plan_content,json=planContent,proto3" json:"plan_content,omitempty"`
	// Solutions to request per seed; 0 means the server default.
	NumSolutions  int32 `protobuf:"varint,3,opt,name=num_solutions,json=numSolutions,proto3" json:"num_solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIKSolutionsRequest) Reset() {
	*x = GetIKSolutionsRequest{}
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIKSolutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIKSolutionsRequest) ProtoMessage() {}

func (x *GetIKSolutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIKSolutionsRequest.ProtoReflect.Descriptor instead.
func (*GetIKSolutionsRequest) Descriptor() ([]byte, []int) {
	return file_motionplan_v1_motionplan_proto_rawDescGZIP(), []int{0}
}

func (x *GetIKSolutionsRequest) GetPlanContent() []byte {
	if x != nil {
		return x.PlanContent
	}
	return nil
}

func (x *GetIKSolutionsRequest) GetNumSolutions() int32 {
	if x != nil {
		return x.NumSolutions
	}
	return 0
}

type GetIKSolutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*IKSeedResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIKSolutionsResponse) Reset() {
	*x = GetIKSolutionsResponse{}
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIKSolutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIKSolutionsResponse) ProtoMessage() {}

func (x *GetIKSolutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIKSolutionsResponse.ProtoReflect.Descriptor instead.
func (*GetIKSolutionsResponse) Descriptor() ([]byte, []int) {
	return file_motionplan_v1_motionplan_proto_rawDescGZIP(), []int{1}
}

func (x *GetIKSolutionsResponse) GetResults() []*IKSeedResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type IKSeedResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Solutions     []*IKSolution          `protobuf:"bytes,2,rep,name=solutions,proto3" json:"solutions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IKSeedResult) Reset() {
	*x = IKSeedResult{}
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IKSeedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IKSeedResult) ProtoMessage() {}

func (x *IKSeedResult) ProtoReflect() protoreflect.Message {
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IKSeedResult.ProtoReflect.Descriptor instead.
func (*IKSeedResult) Descriptor() ([]byte, []int) {
	return file_motionplan_v1_motionplan_proto_rawDescGZIP(), []int{2}
}

func (x *IKSeedResult) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *IKSeedResult) GetSolutions() []*IKSolution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

type IKSolution struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Cost               float64                    `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Configuration      map[string]*JointPositions `protobuf:"bytes,2,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfigurationValid bool                       `protobuf:"varint,3,opt,name=configuration_valid,json=configurationValid,proto3" json:"configuration_valid,omitempty"`
	ConfigurationError *string                    `protobuf:"bytes,4,opt,name=configuration_error,json=configurationError,proto3,oneof" json:"configuration_error,omitempty"`
	CheckpathValid     *bool                      `protobuf:"varint,5,opt,name=checkpath_valid,json=checkpathValid,proto3,oneof" json:"checkpath_valid,omitempty"`
	FirstError         *string                    `protobuf:"bytes,6,opt,name=first_error,json=firstError,proto3,oneof" json:"first_error,omitempty"`
	LastGoodInputs     map[string]*JointPositions `protobuf:"bytes,7,rep,name=last_good_inputs,json=lastGoodInputs,proto3" json:"last_good_inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether first_error was a collision (obstacle or self) rather than another
	// constraint violation. Set only alongside first_error.
	IsObstacleCollision *bool `protobuf:"varint,8,opt,name=is_obstacle_collision,json=isObstacleCollision,proto3,oneof" json:"is_obstacle_collision,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IKSolution) Reset() {
	*x = IKSolution{}
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IKSolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IKSolution) ProtoMessage() {}

func (x *IKSolution) ProtoReflect() protoreflect.Message {
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IKSolution.ProtoReflect.Descriptor instead.
func (*IKSolution) Descriptor() ([]byte, []int) {
	return file_motionplan_v1_motionplan_proto_rawDescGZIP(), []int{3}
}

func (x *IKSolution) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *IKSolution) GetConfiguration() map[string]*JointPositions {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *IKSolution) GetConfigurationValid() bool {
	if x != nil {
		return x.ConfigurationValid
	}
	return false
}

func (x *IKSolution) GetConfigurationError() string {
	if x != nil && x.ConfigurationError != nil {
		return *x.ConfigurationError
	}
	return ""
}

func (x *IKSolution) GetCheckpathValid() bool {
	if x != nil && x.CheckpathValid != nil {
		return *x.CheckpathValid
	}
	return false
}

func (x *IKSolution) GetFirstError() string {
	if x != nil && x.FirstError != nil {
		return *x.FirstError
	}
	return ""
}

func (x *IKSolution) GetLastGoodInputs() map[string]*JointPositions {
	if x != nil {
		return x.LastGoodInputs
	}
	return nil
}

func (x *IKSolution) GetIsObstacleCollision() bool {
	if x != nil && x.IsObstacleCollision != nil {
		return *x.IsObstacleCollision
	}
	return false
}

type JointPositions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JointPositions) Reset() {
	*x = JointPositions{}
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JointPositions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JointPositions) ProtoMessage() {}

func (x *JointPositions) ProtoReflect() protoreflect.Message {
	mi := &file_motionplan_v1_motionplan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JointPositions.ProtoReflect.Descriptor instead.
func (*JointPositions) Descriptor() ([]byte, []int) {
	return file_motionplan_v1_motionplan_proto_rawDescGZIP(), []int{4}
}

func (x *JointPositions) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_motionplan_v1_motionplan_proto protoreflect.FileDescriptor

const file_motionplan_v1_motionplan_proto_rawDesc = "" +
	"\n" +
	"\x1emotionplan/v1/motionplan.proto\x12\rmotionplan.v1\"e\n" +
	"\x15GetIKSolutionsRequest\x12!\n" +
	"\fplan_content\x18\x02 \x01(\fR\vplanContent\x12#\n" +
	"\rnum_solutions\x18\x03 \x01(\x05R\fnumSolutionsJ\x04\b\x01\x10\x02\"O\n" +
	"\x16GetIKSolutionsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.motionplan.v1.IKSeedResultR\aresults\"[\n" +
	"\fIKSeedResult\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x127\n" +
	"\tsolutions\x18\x02 \x03(\v2\x19.motionplan.v1.IKSolutionR\tsolutions\"\xda\x05\n" +
	"\n" +
	"IKSolution\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\x01R\x04cost\x12R\n" +
	"\rconfiguration\x18\x02 \x03(\v2,.motionplan.v1.IKSolution.ConfigurationEntryR\rconfiguration\x12/\n" +
	"\x13configuration_valid\x18\x03 \x01(\bR\x12configurationValid\x124\n" +
	"\x13configuration_error\x18\x04 \x01(\tH\x00R\x12configurationError\x88\x01\x01\x12,\n" +
	"\x0fcheckpath_valid\x18\x05 \x01(\bH\x01R\x0echeckpathValid\x88\x01\x01\x12$\n" +
	"\vfirst_error\x18\x06 \x01(\tH\x02R\n" +
	"firstError\x88\x01\x01\x12W\n" +
	"\x10last_good_inputs\x18\a \x03(\v2-.motionplan.v1.IKSolution.LastGoodInputsEntryR\x0elastGoodInputs\x127\n" +
	"\x15is_obstacle_collision\x18\b \x01(\bH\x03R\x13isObstacleCollision\x88\x01\x01\x1a_\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.motionplan.v1.JointPositionsR\x05value:\x028\x01\x1a`\n" +
	"\x13LastGoodInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.motionplan.v1.JointPositionsR\x05value:\x028\x01B\x16\n" +
	"\x14_configuration_errorB\x12\n" +
	"\x10_checkpath_validB\x0e\n" +
	"\f_first_errorB\x18\n" +
	"\x16_is_obstacle_collision\"(\n" +
	"\x0eJointPositions\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values2r\n" +
	"\x11MotionPlanService\x12]\n" +
	"\x0eGetIKSolutions\x12$.motionplan.v1.GetIKSolutionsRequest\x1a%.motionplan.v1.GetIKSolutionsResponseBBZ@github.com/viamrobotics/visualization/motionplan/v1;motionplanv1b\x06proto3"

var (
	file_motionplan_v1_motionplan_proto_rawDescOnce sync.Once
	file_motionplan_v1_motionplan_proto_rawDescData []byte
)

func file_motionplan_v1_motionplan_proto_rawDescGZIP() []byte {
	file_motionplan_v1_motionplan_proto_rawDescOnce.Do(func() {
		file_motionplan_v1_motionplan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_motionplan_v1_motionplan_proto_rawDesc), len(file_motionplan_v1_motionplan_proto_rawDesc)))
	})
	return file_motionplan_v1_motionplan_proto_rawDescData
}

var file_motionplan_v1_motionplan_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_motionplan_v1_motionplan_proto_goTypes = []any{
	(*GetIKSolutionsRequest)(nil),  // 0: motionplan.v1.GetIKSolutionsRequest
	(*GetIKSolutionsResponse)(nil), // 1: motionplan.v1.GetIKSolutionsResponse
	(*IKSeedResult)(nil),           // 2: motionplan.v1.IKSeedResult
	(*IKSolution)(nil),             // 3: motionplan.v1.IKSolution
	(*JointPositions)(nil),         // 4: motionplan.v1.JointPositions
	nil,                            // 5: motionplan.v1.IKSolution.ConfigurationEntry
	nil,                            // 6: motionplan.v1.IKSolution.LastGoodInputsEntry
}
var file_motionplan_v1_motionplan_proto_depIdxs = []int32{
	2, // 0: motionplan.v1.GetIKSolutionsResponse.results:type_name -> motionplan.v1.IKSeedResult
	3, // 1: motionplan.v1.IKSeedResult.solutions:type_name -> motionplan.v1.IKSolution
	5, // 2: motionplan.v1.IKSolution.configuration:type_name -> motionplan.v1.IKSolution.ConfigurationEntry
	6, // 3: motionplan.v1.IKSolution.last_good_inputs:type_name -> motionplan.v1.IKSolution.LastGoodInputsEntry
	4, // 4: motionplan.v1.IKSolution.ConfigurationEntry.value:type_name -> motionplan.v1.JointPositions
	4, // 5: motionplan.v1.IKSolution.LastGoodInputsEntry.value:type_name -> motionplan.v1.JointPositions
	0, // 6: motionplan.v1.MotionPlanService.GetIKSolutions:input_type -> motionplan.v1.GetIKSolutionsRequest
	1, // 7: motionplan.v1.MotionPlanService.GetIKSolutions:output_type -> motionplan.v1.GetIKSolutionsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_motionplan_v1_motionplan_proto_init() }
func file_motionplan_v1_motionplan_proto_init() {
	if File_motionplan_v1_motionplan_proto != nil {
		return
	}
	file_motionplan_v1_motionplan_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_motionplan_v1_motionplan_proto_rawDesc), len(file_motionplan_v1_motionplan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_motionplan_v1_motionplan_proto_goTypes,
		DependencyIndexes: file_motionplan_v1_motionplan_proto_depIdxs,
		MessageInfos:      file_motionplan_v1_motionplan_proto_msgTypes,
	}.Build()
	File_motionplan_v1_motionplan_proto = out.File
	file_motionplan_v1_motionplan_proto_goTypes = nil
	file_motionplan_v1_motionplan_proto_depIdxs = nil
}
