package draw

import (
	"testing"

	"github.com/golang/geo/r3"
	"go.viam.com/rdk/referenceframe"
	"go.viam.com/rdk/spatialmath"
	"go.viam.com/test"
)

// 3 control points, degree 3 → knots length = 3 + 3 + 1 = 7
var nurbsControlPoints = []spatialmath.Pose{
	spatialmath.NewPose(r3.Vector{X: 0, Y: 0, Z: 0}, &spatialmath.OrientationVectorDegrees{OX: 0, OY: 0, OZ: 1, Theta: 0}),
	spatialmath.NewPose(r3.Vector{X: 1, Y: 0, Z: 0}, &spatialmath.OrientationVectorDegrees{OX: 0, OY: 0, OZ: 1, Theta: 0}),
	spatialmath.NewPose(r3.Vector{X: 0, Y: 1, Z: 0}, &spatialmath.OrientationVectorDegrees{OX: 0, OY: 0, OZ: 1, Theta: 0}),
}

var nurbsKnotsDefault = []float64{0, 0, 0, 0, 1, 1, 1} // degree 3, 3 control points

// degree 1, 3 control points → knots length = 3 + 1 + 1 = 5
var nurbsKnotsDegree1 = []float64{0, 0, 0, 0, 0}

func TestNewNurbs(t *testing.T) {
	t.Run("Defaults", func(t *testing.T) {
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault)
		test.That(t, err, test.ShouldBeNil)
		test.That(t, nurbs.Degree, test.ShouldEqual, DefaultNurbsDegree)
		test.That(t, nurbs.Color, test.ShouldResemble, DefaultNurbsColor)
		// auto-generated uniform weights
		test.That(t, nurbs.Weights, test.ShouldResemble, []float64{1, 1, 1})
	})

	t.Run("WithNurbsDegree", func(t *testing.T) {
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDegree1, WithNurbsDegree(1))
		test.That(t, err, test.ShouldBeNil)
		test.That(t, nurbs.Degree, test.ShouldEqual, int32(1))
	})

	t.Run("WithNurbsWeights", func(t *testing.T) {
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsWeights([]float64{1, 2, 3}))
		test.That(t, err, test.ShouldBeNil)
		test.That(t, nurbs.Weights, test.ShouldResemble, []float64{1, 2, 3})
	})

	t.Run("WithNurbsWeights_AutoGenerated", func(t *testing.T) {
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsWeights(nil))
		test.That(t, err, test.ShouldBeNil)
		test.That(t, nurbs.Weights, test.ShouldResemble, []float64{1, 1, 1})
	})

	t.Run("WithNurbsColors_Single", func(t *testing.T) {
		red := NewColor(WithName("red"))
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsColors(red))
		test.That(t, err, test.ShouldBeNil)
		test.That(t, nurbs.Color, test.ShouldResemble, red)
	})

	t.Run("WithNurbsColors_PerPoint", func(t *testing.T) {
		red := NewColor(WithName("red"))
		green := NewColor(WithName("green"))
		blue := NewColor(WithName("blue"))
		nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsColors(red, green, blue))
		test.That(t, err, test.ShouldBeNil)
		// Color field holds the first (default) color
		test.That(t, nurbs.Color, test.ShouldResemble, red)
	})

	t.Run("ErrorEmptyControlPoints", func(t *testing.T) {
		_, err := NewNurbs([]spatialmath.Pose{}, nurbsKnotsDefault)
		test.That(t, err, test.ShouldNotBeNil)
		test.That(t, err.Error(), test.ShouldContainSubstring, "control points cannot be empty")
	})

	t.Run("ErrorEmptyKnots", func(t *testing.T) {
		_, err := NewNurbs(nurbsControlPoints, []float64{})
		test.That(t, err, test.ShouldNotBeNil)
		test.That(t, err.Error(), test.ShouldContainSubstring, "knots cannot be empty")
	})

	t.Run("ErrorMismatchedWeightsLength", func(t *testing.T) {
		_, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsWeights([]float64{1, 2}))
		test.That(t, err, test.ShouldNotBeNil)
		test.That(t, err.Error(), test.ShouldContainSubstring, "weights must have length 3, got 2")
	})

	t.Run("ErrorMismatchedColorsLength", func(t *testing.T) {
		red := NewColor(WithName("red"))
		green := NewColor(WithName("green"))
		_, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsColors(red, green))
		test.That(t, err, test.ShouldNotBeNil)
		test.That(t, err.Error(), test.ShouldContainSubstring, "colors must have length 1 (single color) or 3 (per-control-point colors), got 2")
	})

	t.Run("ErrorWrongKnotsLength", func(t *testing.T) {
		// degree 3, 3 control points → needs 7 knots, providing 5
		_, err := NewNurbs(nurbsControlPoints, []float64{0, 0, 0, 0, 0})
		test.That(t, err, test.ShouldNotBeNil)
		test.That(t, err.Error(), test.ShouldContainSubstring, "knots must have length 7, got 5")
	})
}

func TestNurbs_Draw(t *testing.T) {
	red := NewColor(WithName("red"))
	nurbs, err := NewNurbs(nurbsControlPoints, nurbsKnotsDefault, WithNurbsColors(red))
	test.That(t, err, test.ShouldBeNil)

	t.Run("DrawingDefaults", func(t *testing.T) {
		drawing := nurbs.Draw("test-nurbs")
		test.That(t, drawing.Name, test.ShouldEqual, "test-nurbs")
		test.That(t, drawing.Parent, test.ShouldEqual, referenceframe.World)
		test.That(t, drawing.Pose, test.ShouldResemble, spatialmath.NewZeroPose())
		test.That(t, drawing.Shape.Center, test.ShouldResemble, spatialmath.NewZeroPose())
		test.That(t, drawing.Shape.Label, test.ShouldEqual, "test-nurbs")
		test.That(t, drawing.Shape.Nurbs, test.ShouldNotBeNil)
	})

	t.Run("DrawWithPose", func(t *testing.T) {
		pose := spatialmath.NewPose(r3.Vector{X: 10, Y: 0, Z: 0}, &spatialmath.OrientationVectorDegrees{OX: 0, OY: 0, OZ: 1, Theta: 0})
		drawing := nurbs.Draw("test-nurbs", WithPose(pose))
		test.That(t, drawing.Pose, test.ShouldResemble, pose)
		test.That(t, drawing.Shape.Center, test.ShouldResemble, spatialmath.NewZeroPose())
	})

	t.Run("DrawWithParent", func(t *testing.T) {
		drawing := nurbs.Draw("test-nurbs", WithParent("robot-base"))
		test.That(t, drawing.Parent, test.ShouldEqual, "robot-base")
	})

	t.Run("ProtoOutput", func(t *testing.T) {
		drawing := nurbs.Draw("test-nurbs")
		proto := drawing.ToProto()
		test.That(t, proto.ReferenceFrame, test.ShouldEqual, "test-nurbs")
		test.That(t, proto.PoseInObserverFrame.ReferenceFrame, test.ShouldEqual, referenceframe.World)
		test.That(t, proto.PhysicalObject, test.ShouldNotBeNil)
		test.That(t, proto.PhysicalObject.Label, test.ShouldEqual, "test-nurbs")
		protoNurbs := proto.PhysicalObject.GetNurbs()
		test.That(t, protoNurbs, test.ShouldNotBeNil)
		test.That(t, *protoNurbs.Degree, test.ShouldEqual, int32(3))
		// red (255, 0, 0, 255) packed as [r, g, b, a]
		test.That(t, proto.Metadata.Colors, test.ShouldResemble, []byte{0xff, 0x00, 0x00, 0xff})
	})
}
