// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: draw/v1/service.proto

package drawv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/viam-labs/motion-tools/draw/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DrawServiceName is the fully-qualified name of the DrawService service.
	DrawServiceName = "draw.v1.DrawService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DrawServiceAddTransformProcedure is the fully-qualified name of the DrawService's AddTransform
	// RPC.
	DrawServiceAddTransformProcedure = "/draw.v1.DrawService/AddTransform"
	// DrawServiceUpdateTransformProcedure is the fully-qualified name of the DrawService's
	// UpdateTransform RPC.
	DrawServiceUpdateTransformProcedure = "/draw.v1.DrawService/UpdateTransform"
	// DrawServiceRemoveTransformProcedure is the fully-qualified name of the DrawService's
	// RemoveTransform RPC.
	DrawServiceRemoveTransformProcedure = "/draw.v1.DrawService/RemoveTransform"
	// DrawServiceRemoveAllTransformsProcedure is the fully-qualified name of the DrawService's
	// RemoveAllTransforms RPC.
	DrawServiceRemoveAllTransformsProcedure = "/draw.v1.DrawService/RemoveAllTransforms"
	// DrawServiceStreamTransformChangesProcedure is the fully-qualified name of the DrawService's
	// StreamTransformChanges RPC.
	DrawServiceStreamTransformChangesProcedure = "/draw.v1.DrawService/StreamTransformChanges"
	// DrawServiceAddDrawingProcedure is the fully-qualified name of the DrawService's AddDrawing RPC.
	DrawServiceAddDrawingProcedure = "/draw.v1.DrawService/AddDrawing"
	// DrawServiceUpdateDrawingProcedure is the fully-qualified name of the DrawService's UpdateDrawing
	// RPC.
	DrawServiceUpdateDrawingProcedure = "/draw.v1.DrawService/UpdateDrawing"
	// DrawServiceRemoveDrawingProcedure is the fully-qualified name of the DrawService's RemoveDrawing
	// RPC.
	DrawServiceRemoveDrawingProcedure = "/draw.v1.DrawService/RemoveDrawing"
	// DrawServiceRemoveAllDrawingsProcedure is the fully-qualified name of the DrawService's
	// RemoveAllDrawings RPC.
	DrawServiceRemoveAllDrawingsProcedure = "/draw.v1.DrawService/RemoveAllDrawings"
	// DrawServiceStreamDrawingChangesProcedure is the fully-qualified name of the DrawService's
	// StreamDrawingChanges RPC.
	DrawServiceStreamDrawingChangesProcedure = "/draw.v1.DrawService/StreamDrawingChanges"
	// DrawServiceStreamSceneChangesProcedure is the fully-qualified name of the DrawService's
	// StreamSceneChanges RPC.
	DrawServiceStreamSceneChangesProcedure = "/draw.v1.DrawService/StreamSceneChanges"
	// DrawServiceSetSceneMetadataProcedure is the fully-qualified name of the DrawService's
	// SetSceneMetadata RPC.
	DrawServiceSetSceneMetadataProcedure = "/draw.v1.DrawService/SetSceneMetadata"
	// DrawServiceRemoveAllProcedure is the fully-qualified name of the DrawService's RemoveAll RPC.
	DrawServiceRemoveAllProcedure = "/draw.v1.DrawService/RemoveAll"
)

// DrawServiceClient is a client for the draw.v1.DrawService service.
type DrawServiceClient interface {
	AddTransform(context.Context, *connect.Request[v1.AddTransformRequest]) (*connect.Response[v1.AddTransformResponse], error)
	UpdateTransform(context.Context, *connect.Request[v1.UpdateTransformRequest]) (*connect.Response[v1.UpdateTransformResponse], error)
	RemoveTransform(context.Context, *connect.Request[v1.RemoveTransformRequest]) (*connect.Response[v1.RemoveTransformResponse], error)
	RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error)
	StreamTransformChanges(context.Context, *connect.Request[v1.StreamTransformChangesRequest]) (*connect.ServerStreamForClient[v1.StreamTransformChangesResponse], error)
	AddDrawing(context.Context, *connect.Request[v1.AddDrawingRequest]) (*connect.Response[v1.AddDrawingResponse], error)
	UpdateDrawing(context.Context, *connect.Request[v1.UpdateDrawingRequest]) (*connect.Response[v1.UpdateDrawingResponse], error)
	RemoveDrawing(context.Context, *connect.Request[v1.RemoveDrawingRequest]) (*connect.Response[v1.RemoveDrawingResponse], error)
	RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error)
	StreamDrawingChanges(context.Context, *connect.Request[v1.StreamDrawingChangesRequest]) (*connect.ServerStreamForClient[v1.StreamDrawingChangesResponse], error)
	StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest]) (*connect.ServerStreamForClient[v1.StreamSceneChangesResponse], error)
	SetSceneMetadata(context.Context, *connect.Request[v1.SetSceneMetadataRequest]) (*connect.Response[v1.SetSceneMetadataResponse], error)
	RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error)
}

// NewDrawServiceClient constructs a client for the draw.v1.DrawService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDrawServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DrawServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	drawServiceMethods := v1.File_draw_v1_service_proto.Services().ByName("DrawService").Methods()
	return &drawServiceClient{
		addTransform: connect.NewClient[v1.AddTransformRequest, v1.AddTransformResponse](
			httpClient,
			baseURL+DrawServiceAddTransformProcedure,
			connect.WithSchema(drawServiceMethods.ByName("AddTransform")),
			connect.WithClientOptions(opts...),
		),
		updateTransform: connect.NewClient[v1.UpdateTransformRequest, v1.UpdateTransformResponse](
			httpClient,
			baseURL+DrawServiceUpdateTransformProcedure,
			connect.WithSchema(drawServiceMethods.ByName("UpdateTransform")),
			connect.WithClientOptions(opts...),
		),
		removeTransform: connect.NewClient[v1.RemoveTransformRequest, v1.RemoveTransformResponse](
			httpClient,
			baseURL+DrawServiceRemoveTransformProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveTransform")),
			connect.WithClientOptions(opts...),
		),
		removeAllTransforms: connect.NewClient[v1.RemoveAllTransformsRequest, v1.RemoveAllTransformsResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllTransformsProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAllTransforms")),
			connect.WithClientOptions(opts...),
		),
		streamTransformChanges: connect.NewClient[v1.StreamTransformChangesRequest, v1.StreamTransformChangesResponse](
			httpClient,
			baseURL+DrawServiceStreamTransformChangesProcedure,
			connect.WithSchema(drawServiceMethods.ByName("StreamTransformChanges")),
			connect.WithClientOptions(opts...),
		),
		addDrawing: connect.NewClient[v1.AddDrawingRequest, v1.AddDrawingResponse](
			httpClient,
			baseURL+DrawServiceAddDrawingProcedure,
			connect.WithSchema(drawServiceMethods.ByName("AddDrawing")),
			connect.WithClientOptions(opts...),
		),
		updateDrawing: connect.NewClient[v1.UpdateDrawingRequest, v1.UpdateDrawingResponse](
			httpClient,
			baseURL+DrawServiceUpdateDrawingProcedure,
			connect.WithSchema(drawServiceMethods.ByName("UpdateDrawing")),
			connect.WithClientOptions(opts...),
		),
		removeDrawing: connect.NewClient[v1.RemoveDrawingRequest, v1.RemoveDrawingResponse](
			httpClient,
			baseURL+DrawServiceRemoveDrawingProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveDrawing")),
			connect.WithClientOptions(opts...),
		),
		removeAllDrawings: connect.NewClient[v1.RemoveAllDrawingsRequest, v1.RemoveAllDrawingsResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllDrawingsProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAllDrawings")),
			connect.WithClientOptions(opts...),
		),
		streamDrawingChanges: connect.NewClient[v1.StreamDrawingChangesRequest, v1.StreamDrawingChangesResponse](
			httpClient,
			baseURL+DrawServiceStreamDrawingChangesProcedure,
			connect.WithSchema(drawServiceMethods.ByName("StreamDrawingChanges")),
			connect.WithClientOptions(opts...),
		),
		streamSceneChanges: connect.NewClient[v1.StreamSceneChangesRequest, v1.StreamSceneChangesResponse](
			httpClient,
			baseURL+DrawServiceStreamSceneChangesProcedure,
			connect.WithSchema(drawServiceMethods.ByName("StreamSceneChanges")),
			connect.WithClientOptions(opts...),
		),
		setSceneMetadata: connect.NewClient[v1.SetSceneMetadataRequest, v1.SetSceneMetadataResponse](
			httpClient,
			baseURL+DrawServiceSetSceneMetadataProcedure,
			connect.WithSchema(drawServiceMethods.ByName("SetSceneMetadata")),
			connect.WithClientOptions(opts...),
		),
		removeAll: connect.NewClient[v1.RemoveAllRequest, v1.RemoveAllResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// drawServiceClient implements DrawServiceClient.
type drawServiceClient struct {
	addTransform           *connect.Client[v1.AddTransformRequest, v1.AddTransformResponse]
	updateTransform        *connect.Client[v1.UpdateTransformRequest, v1.UpdateTransformResponse]
	removeTransform        *connect.Client[v1.RemoveTransformRequest, v1.RemoveTransformResponse]
	removeAllTransforms    *connect.Client[v1.RemoveAllTransformsRequest, v1.RemoveAllTransformsResponse]
	streamTransformChanges *connect.Client[v1.StreamTransformChangesRequest, v1.StreamTransformChangesResponse]
	addDrawing             *connect.Client[v1.AddDrawingRequest, v1.AddDrawingResponse]
	updateDrawing          *connect.Client[v1.UpdateDrawingRequest, v1.UpdateDrawingResponse]
	removeDrawing          *connect.Client[v1.RemoveDrawingRequest, v1.RemoveDrawingResponse]
	removeAllDrawings      *connect.Client[v1.RemoveAllDrawingsRequest, v1.RemoveAllDrawingsResponse]
	streamDrawingChanges   *connect.Client[v1.StreamDrawingChangesRequest, v1.StreamDrawingChangesResponse]
	streamSceneChanges     *connect.Client[v1.StreamSceneChangesRequest, v1.StreamSceneChangesResponse]
	setSceneMetadata       *connect.Client[v1.SetSceneMetadataRequest, v1.SetSceneMetadataResponse]
	removeAll              *connect.Client[v1.RemoveAllRequest, v1.RemoveAllResponse]
}

// AddTransform calls draw.v1.DrawService.AddTransform.
func (c *drawServiceClient) AddTransform(ctx context.Context, req *connect.Request[v1.AddTransformRequest]) (*connect.Response[v1.AddTransformResponse], error) {
	return c.addTransform.CallUnary(ctx, req)
}

// UpdateTransform calls draw.v1.DrawService.UpdateTransform.
func (c *drawServiceClient) UpdateTransform(ctx context.Context, req *connect.Request[v1.UpdateTransformRequest]) (*connect.Response[v1.UpdateTransformResponse], error) {
	return c.updateTransform.CallUnary(ctx, req)
}

// RemoveTransform calls draw.v1.DrawService.RemoveTransform.
func (c *drawServiceClient) RemoveTransform(ctx context.Context, req *connect.Request[v1.RemoveTransformRequest]) (*connect.Response[v1.RemoveTransformResponse], error) {
	return c.removeTransform.CallUnary(ctx, req)
}

// RemoveAllTransforms calls draw.v1.DrawService.RemoveAllTransforms.
func (c *drawServiceClient) RemoveAllTransforms(ctx context.Context, req *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error) {
	return c.removeAllTransforms.CallUnary(ctx, req)
}

// StreamTransformChanges calls draw.v1.DrawService.StreamTransformChanges.
func (c *drawServiceClient) StreamTransformChanges(ctx context.Context, req *connect.Request[v1.StreamTransformChangesRequest]) (*connect.ServerStreamForClient[v1.StreamTransformChangesResponse], error) {
	return c.streamTransformChanges.CallServerStream(ctx, req)
}

// AddDrawing calls draw.v1.DrawService.AddDrawing.
func (c *drawServiceClient) AddDrawing(ctx context.Context, req *connect.Request[v1.AddDrawingRequest]) (*connect.Response[v1.AddDrawingResponse], error) {
	return c.addDrawing.CallUnary(ctx, req)
}

// UpdateDrawing calls draw.v1.DrawService.UpdateDrawing.
func (c *drawServiceClient) UpdateDrawing(ctx context.Context, req *connect.Request[v1.UpdateDrawingRequest]) (*connect.Response[v1.UpdateDrawingResponse], error) {
	return c.updateDrawing.CallUnary(ctx, req)
}

// RemoveDrawing calls draw.v1.DrawService.RemoveDrawing.
func (c *drawServiceClient) RemoveDrawing(ctx context.Context, req *connect.Request[v1.RemoveDrawingRequest]) (*connect.Response[v1.RemoveDrawingResponse], error) {
	return c.removeDrawing.CallUnary(ctx, req)
}

// RemoveAllDrawings calls draw.v1.DrawService.RemoveAllDrawings.
func (c *drawServiceClient) RemoveAllDrawings(ctx context.Context, req *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error) {
	return c.removeAllDrawings.CallUnary(ctx, req)
}

// StreamDrawingChanges calls draw.v1.DrawService.StreamDrawingChanges.
func (c *drawServiceClient) StreamDrawingChanges(ctx context.Context, req *connect.Request[v1.StreamDrawingChangesRequest]) (*connect.ServerStreamForClient[v1.StreamDrawingChangesResponse], error) {
	return c.streamDrawingChanges.CallServerStream(ctx, req)
}

// StreamSceneChanges calls draw.v1.DrawService.StreamSceneChanges.
func (c *drawServiceClient) StreamSceneChanges(ctx context.Context, req *connect.Request[v1.StreamSceneChangesRequest]) (*connect.ServerStreamForClient[v1.StreamSceneChangesResponse], error) {
	return c.streamSceneChanges.CallServerStream(ctx, req)
}

// SetSceneMetadata calls draw.v1.DrawService.SetSceneMetadata.
func (c *drawServiceClient) SetSceneMetadata(ctx context.Context, req *connect.Request[v1.SetSceneMetadataRequest]) (*connect.Response[v1.SetSceneMetadataResponse], error) {
	return c.setSceneMetadata.CallUnary(ctx, req)
}

// RemoveAll calls draw.v1.DrawService.RemoveAll.
func (c *drawServiceClient) RemoveAll(ctx context.Context, req *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error) {
	return c.removeAll.CallUnary(ctx, req)
}

// DrawServiceHandler is an implementation of the draw.v1.DrawService service.
type DrawServiceHandler interface {
	AddTransform(context.Context, *connect.Request[v1.AddTransformRequest]) (*connect.Response[v1.AddTransformResponse], error)
	UpdateTransform(context.Context, *connect.Request[v1.UpdateTransformRequest]) (*connect.Response[v1.UpdateTransformResponse], error)
	RemoveTransform(context.Context, *connect.Request[v1.RemoveTransformRequest]) (*connect.Response[v1.RemoveTransformResponse], error)
	RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error)
	StreamTransformChanges(context.Context, *connect.Request[v1.StreamTransformChangesRequest], *connect.ServerStream[v1.StreamTransformChangesResponse]) error
	AddDrawing(context.Context, *connect.Request[v1.AddDrawingRequest]) (*connect.Response[v1.AddDrawingResponse], error)
	UpdateDrawing(context.Context, *connect.Request[v1.UpdateDrawingRequest]) (*connect.Response[v1.UpdateDrawingResponse], error)
	RemoveDrawing(context.Context, *connect.Request[v1.RemoveDrawingRequest]) (*connect.Response[v1.RemoveDrawingResponse], error)
	RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error)
	StreamDrawingChanges(context.Context, *connect.Request[v1.StreamDrawingChangesRequest], *connect.ServerStream[v1.StreamDrawingChangesResponse]) error
	StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest], *connect.ServerStream[v1.StreamSceneChangesResponse]) error
	SetSceneMetadata(context.Context, *connect.Request[v1.SetSceneMetadataRequest]) (*connect.Response[v1.SetSceneMetadataResponse], error)
	RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error)
}

// NewDrawServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDrawServiceHandler(svc DrawServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	drawServiceMethods := v1.File_draw_v1_service_proto.Services().ByName("DrawService").Methods()
	drawServiceAddTransformHandler := connect.NewUnaryHandler(
		DrawServiceAddTransformProcedure,
		svc.AddTransform,
		connect.WithSchema(drawServiceMethods.ByName("AddTransform")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceUpdateTransformHandler := connect.NewUnaryHandler(
		DrawServiceUpdateTransformProcedure,
		svc.UpdateTransform,
		connect.WithSchema(drawServiceMethods.ByName("UpdateTransform")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveTransformHandler := connect.NewUnaryHandler(
		DrawServiceRemoveTransformProcedure,
		svc.RemoveTransform,
		connect.WithSchema(drawServiceMethods.ByName("RemoveTransform")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllTransformsHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllTransformsProcedure,
		svc.RemoveAllTransforms,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAllTransforms")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceStreamTransformChangesHandler := connect.NewServerStreamHandler(
		DrawServiceStreamTransformChangesProcedure,
		svc.StreamTransformChanges,
		connect.WithSchema(drawServiceMethods.ByName("StreamTransformChanges")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceAddDrawingHandler := connect.NewUnaryHandler(
		DrawServiceAddDrawingProcedure,
		svc.AddDrawing,
		connect.WithSchema(drawServiceMethods.ByName("AddDrawing")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceUpdateDrawingHandler := connect.NewUnaryHandler(
		DrawServiceUpdateDrawingProcedure,
		svc.UpdateDrawing,
		connect.WithSchema(drawServiceMethods.ByName("UpdateDrawing")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveDrawingHandler := connect.NewUnaryHandler(
		DrawServiceRemoveDrawingProcedure,
		svc.RemoveDrawing,
		connect.WithSchema(drawServiceMethods.ByName("RemoveDrawing")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllDrawingsHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllDrawingsProcedure,
		svc.RemoveAllDrawings,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAllDrawings")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceStreamDrawingChangesHandler := connect.NewServerStreamHandler(
		DrawServiceStreamDrawingChangesProcedure,
		svc.StreamDrawingChanges,
		connect.WithSchema(drawServiceMethods.ByName("StreamDrawingChanges")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceStreamSceneChangesHandler := connect.NewServerStreamHandler(
		DrawServiceStreamSceneChangesProcedure,
		svc.StreamSceneChanges,
		connect.WithSchema(drawServiceMethods.ByName("StreamSceneChanges")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceSetSceneMetadataHandler := connect.NewUnaryHandler(
		DrawServiceSetSceneMetadataProcedure,
		svc.SetSceneMetadata,
		connect.WithSchema(drawServiceMethods.ByName("SetSceneMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllProcedure,
		svc.RemoveAll,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/draw.v1.DrawService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DrawServiceAddTransformProcedure:
			drawServiceAddTransformHandler.ServeHTTP(w, r)
		case DrawServiceUpdateTransformProcedure:
			drawServiceUpdateTransformHandler.ServeHTTP(w, r)
		case DrawServiceRemoveTransformProcedure:
			drawServiceRemoveTransformHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllTransformsProcedure:
			drawServiceRemoveAllTransformsHandler.ServeHTTP(w, r)
		case DrawServiceStreamTransformChangesProcedure:
			drawServiceStreamTransformChangesHandler.ServeHTTP(w, r)
		case DrawServiceAddDrawingProcedure:
			drawServiceAddDrawingHandler.ServeHTTP(w, r)
		case DrawServiceUpdateDrawingProcedure:
			drawServiceUpdateDrawingHandler.ServeHTTP(w, r)
		case DrawServiceRemoveDrawingProcedure:
			drawServiceRemoveDrawingHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllDrawingsProcedure:
			drawServiceRemoveAllDrawingsHandler.ServeHTTP(w, r)
		case DrawServiceStreamDrawingChangesProcedure:
			drawServiceStreamDrawingChangesHandler.ServeHTTP(w, r)
		case DrawServiceStreamSceneChangesProcedure:
			drawServiceStreamSceneChangesHandler.ServeHTTP(w, r)
		case DrawServiceSetSceneMetadataProcedure:
			drawServiceSetSceneMetadataHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllProcedure:
			drawServiceRemoveAllHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDrawServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDrawServiceHandler struct{}

func (UnimplementedDrawServiceHandler) AddTransform(context.Context, *connect.Request[v1.AddTransformRequest]) (*connect.Response[v1.AddTransformResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.AddTransform is not implemented"))
}

func (UnimplementedDrawServiceHandler) UpdateTransform(context.Context, *connect.Request[v1.UpdateTransformRequest]) (*connect.Response[v1.UpdateTransformResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.UpdateTransform is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveTransform(context.Context, *connect.Request[v1.RemoveTransformRequest]) (*connect.Response[v1.RemoveTransformResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveTransform is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAllTransforms is not implemented"))
}

func (UnimplementedDrawServiceHandler) StreamTransformChanges(context.Context, *connect.Request[v1.StreamTransformChangesRequest], *connect.ServerStream[v1.StreamTransformChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.StreamTransformChanges is not implemented"))
}

func (UnimplementedDrawServiceHandler) AddDrawing(context.Context, *connect.Request[v1.AddDrawingRequest]) (*connect.Response[v1.AddDrawingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.AddDrawing is not implemented"))
}

func (UnimplementedDrawServiceHandler) UpdateDrawing(context.Context, *connect.Request[v1.UpdateDrawingRequest]) (*connect.Response[v1.UpdateDrawingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.UpdateDrawing is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveDrawing(context.Context, *connect.Request[v1.RemoveDrawingRequest]) (*connect.Response[v1.RemoveDrawingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveDrawing is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAllDrawings is not implemented"))
}

func (UnimplementedDrawServiceHandler) StreamDrawingChanges(context.Context, *connect.Request[v1.StreamDrawingChangesRequest], *connect.ServerStream[v1.StreamDrawingChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.StreamDrawingChanges is not implemented"))
}

func (UnimplementedDrawServiceHandler) StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest], *connect.ServerStream[v1.StreamSceneChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.StreamSceneChanges is not implemented"))
}

func (UnimplementedDrawServiceHandler) SetSceneMetadata(context.Context, *connect.Request[v1.SetSceneMetadataRequest]) (*connect.Response[v1.SetSceneMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.SetSceneMetadata is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAll is not implemented"))
}
