// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: draw/v1/service.proto

package drawv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/viam-labs/motion-tools/draw/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DrawServiceName is the fully-qualified name of the DrawService service.
	DrawServiceName = "draw.v1.DrawService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DrawServiceAddEntityProcedure is the fully-qualified name of the DrawService's AddEntity RPC.
	DrawServiceAddEntityProcedure = "/draw.v1.DrawService/AddEntity"
	// DrawServiceUpdateEntityProcedure is the fully-qualified name of the DrawService's UpdateEntity
	// RPC.
	DrawServiceUpdateEntityProcedure = "/draw.v1.DrawService/UpdateEntity"
	// DrawServiceRemoveEntityProcedure is the fully-qualified name of the DrawService's RemoveEntity
	// RPC.
	DrawServiceRemoveEntityProcedure = "/draw.v1.DrawService/RemoveEntity"
	// DrawServiceStreamEntityChangesProcedure is the fully-qualified name of the DrawService's
	// StreamEntityChanges RPC.
	DrawServiceStreamEntityChangesProcedure = "/draw.v1.DrawService/StreamEntityChanges"
	// DrawServiceSetSceneProcedure is the fully-qualified name of the DrawService's SetScene RPC.
	DrawServiceSetSceneProcedure = "/draw.v1.DrawService/SetScene"
	// DrawServiceStreamSceneChangesProcedure is the fully-qualified name of the DrawService's
	// StreamSceneChanges RPC.
	DrawServiceStreamSceneChangesProcedure = "/draw.v1.DrawService/StreamSceneChanges"
	// DrawServiceRemoveAllTransformsProcedure is the fully-qualified name of the DrawService's
	// RemoveAllTransforms RPC.
	DrawServiceRemoveAllTransformsProcedure = "/draw.v1.DrawService/RemoveAllTransforms"
	// DrawServiceRemoveAllDrawingsProcedure is the fully-qualified name of the DrawService's
	// RemoveAllDrawings RPC.
	DrawServiceRemoveAllDrawingsProcedure = "/draw.v1.DrawService/RemoveAllDrawings"
	// DrawServiceRemoveAllProcedure is the fully-qualified name of the DrawService's RemoveAll RPC.
	DrawServiceRemoveAllProcedure = "/draw.v1.DrawService/RemoveAll"
)

// DrawServiceClient is a client for the draw.v1.DrawService service.
type DrawServiceClient interface {
	// Add an entity to the scene.
	AddEntity(context.Context, *connect.Request[v1.AddEntityRequest]) (*connect.Response[v1.AddEntityResponse], error)
	// Update an entity in the scene.
	UpdateEntity(context.Context, *connect.Request[v1.UpdateEntityRequest]) (*connect.Response[v1.UpdateEntityResponse], error)
	// Remove an entity from the scene.
	RemoveEntity(context.Context, *connect.Request[v1.RemoveEntityRequest]) (*connect.Response[v1.RemoveEntityResponse], error)
	// Stream changes to entities in the scene.
	StreamEntityChanges(context.Context, *connect.Request[v1.StreamEntityChangesRequest]) (*connect.ServerStreamForClient[v1.StreamEntityChangesResponse], error)
	// Set the camera and/or metadata for the scene.
	SetScene(context.Context, *connect.Request[v1.SetSceneRequest]) (*connect.Response[v1.SetSceneResponse], error)
	// Stream changes to the camera and/or metadata for the scene.
	StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest]) (*connect.ServerStreamForClient[v1.StreamSceneChangesResponse], error)
	// Remove all transforms from the scene.
	RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error)
	// Remove all drawings from the scene.
	RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error)
	// Remove all entities from the scene.
	RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error)
}

// NewDrawServiceClient constructs a client for the draw.v1.DrawService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDrawServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DrawServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	drawServiceMethods := v1.File_draw_v1_service_proto.Services().ByName("DrawService").Methods()
	return &drawServiceClient{
		addEntity: connect.NewClient[v1.AddEntityRequest, v1.AddEntityResponse](
			httpClient,
			baseURL+DrawServiceAddEntityProcedure,
			connect.WithSchema(drawServiceMethods.ByName("AddEntity")),
			connect.WithClientOptions(opts...),
		),
		updateEntity: connect.NewClient[v1.UpdateEntityRequest, v1.UpdateEntityResponse](
			httpClient,
			baseURL+DrawServiceUpdateEntityProcedure,
			connect.WithSchema(drawServiceMethods.ByName("UpdateEntity")),
			connect.WithClientOptions(opts...),
		),
		removeEntity: connect.NewClient[v1.RemoveEntityRequest, v1.RemoveEntityResponse](
			httpClient,
			baseURL+DrawServiceRemoveEntityProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveEntity")),
			connect.WithClientOptions(opts...),
		),
		streamEntityChanges: connect.NewClient[v1.StreamEntityChangesRequest, v1.StreamEntityChangesResponse](
			httpClient,
			baseURL+DrawServiceStreamEntityChangesProcedure,
			connect.WithSchema(drawServiceMethods.ByName("StreamEntityChanges")),
			connect.WithClientOptions(opts...),
		),
		setScene: connect.NewClient[v1.SetSceneRequest, v1.SetSceneResponse](
			httpClient,
			baseURL+DrawServiceSetSceneProcedure,
			connect.WithSchema(drawServiceMethods.ByName("SetScene")),
			connect.WithClientOptions(opts...),
		),
		streamSceneChanges: connect.NewClient[v1.StreamSceneChangesRequest, v1.StreamSceneChangesResponse](
			httpClient,
			baseURL+DrawServiceStreamSceneChangesProcedure,
			connect.WithSchema(drawServiceMethods.ByName("StreamSceneChanges")),
			connect.WithClientOptions(opts...),
		),
		removeAllTransforms: connect.NewClient[v1.RemoveAllTransformsRequest, v1.RemoveAllTransformsResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllTransformsProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAllTransforms")),
			connect.WithClientOptions(opts...),
		),
		removeAllDrawings: connect.NewClient[v1.RemoveAllDrawingsRequest, v1.RemoveAllDrawingsResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllDrawingsProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAllDrawings")),
			connect.WithClientOptions(opts...),
		),
		removeAll: connect.NewClient[v1.RemoveAllRequest, v1.RemoveAllResponse](
			httpClient,
			baseURL+DrawServiceRemoveAllProcedure,
			connect.WithSchema(drawServiceMethods.ByName("RemoveAll")),
			connect.WithClientOptions(opts...),
		),
	}
}

// drawServiceClient implements DrawServiceClient.
type drawServiceClient struct {
	addEntity           *connect.Client[v1.AddEntityRequest, v1.AddEntityResponse]
	updateEntity        *connect.Client[v1.UpdateEntityRequest, v1.UpdateEntityResponse]
	removeEntity        *connect.Client[v1.RemoveEntityRequest, v1.RemoveEntityResponse]
	streamEntityChanges *connect.Client[v1.StreamEntityChangesRequest, v1.StreamEntityChangesResponse]
	setScene            *connect.Client[v1.SetSceneRequest, v1.SetSceneResponse]
	streamSceneChanges  *connect.Client[v1.StreamSceneChangesRequest, v1.StreamSceneChangesResponse]
	removeAllTransforms *connect.Client[v1.RemoveAllTransformsRequest, v1.RemoveAllTransformsResponse]
	removeAllDrawings   *connect.Client[v1.RemoveAllDrawingsRequest, v1.RemoveAllDrawingsResponse]
	removeAll           *connect.Client[v1.RemoveAllRequest, v1.RemoveAllResponse]
}

// AddEntity calls draw.v1.DrawService.AddEntity.
func (c *drawServiceClient) AddEntity(ctx context.Context, req *connect.Request[v1.AddEntityRequest]) (*connect.Response[v1.AddEntityResponse], error) {
	return c.addEntity.CallUnary(ctx, req)
}

// UpdateEntity calls draw.v1.DrawService.UpdateEntity.
func (c *drawServiceClient) UpdateEntity(ctx context.Context, req *connect.Request[v1.UpdateEntityRequest]) (*connect.Response[v1.UpdateEntityResponse], error) {
	return c.updateEntity.CallUnary(ctx, req)
}

// RemoveEntity calls draw.v1.DrawService.RemoveEntity.
func (c *drawServiceClient) RemoveEntity(ctx context.Context, req *connect.Request[v1.RemoveEntityRequest]) (*connect.Response[v1.RemoveEntityResponse], error) {
	return c.removeEntity.CallUnary(ctx, req)
}

// StreamEntityChanges calls draw.v1.DrawService.StreamEntityChanges.
func (c *drawServiceClient) StreamEntityChanges(ctx context.Context, req *connect.Request[v1.StreamEntityChangesRequest]) (*connect.ServerStreamForClient[v1.StreamEntityChangesResponse], error) {
	return c.streamEntityChanges.CallServerStream(ctx, req)
}

// SetScene calls draw.v1.DrawService.SetScene.
func (c *drawServiceClient) SetScene(ctx context.Context, req *connect.Request[v1.SetSceneRequest]) (*connect.Response[v1.SetSceneResponse], error) {
	return c.setScene.CallUnary(ctx, req)
}

// StreamSceneChanges calls draw.v1.DrawService.StreamSceneChanges.
func (c *drawServiceClient) StreamSceneChanges(ctx context.Context, req *connect.Request[v1.StreamSceneChangesRequest]) (*connect.ServerStreamForClient[v1.StreamSceneChangesResponse], error) {
	return c.streamSceneChanges.CallServerStream(ctx, req)
}

// RemoveAllTransforms calls draw.v1.DrawService.RemoveAllTransforms.
func (c *drawServiceClient) RemoveAllTransforms(ctx context.Context, req *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error) {
	return c.removeAllTransforms.CallUnary(ctx, req)
}

// RemoveAllDrawings calls draw.v1.DrawService.RemoveAllDrawings.
func (c *drawServiceClient) RemoveAllDrawings(ctx context.Context, req *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error) {
	return c.removeAllDrawings.CallUnary(ctx, req)
}

// RemoveAll calls draw.v1.DrawService.RemoveAll.
func (c *drawServiceClient) RemoveAll(ctx context.Context, req *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error) {
	return c.removeAll.CallUnary(ctx, req)
}

// DrawServiceHandler is an implementation of the draw.v1.DrawService service.
type DrawServiceHandler interface {
	// Add an entity to the scene.
	AddEntity(context.Context, *connect.Request[v1.AddEntityRequest]) (*connect.Response[v1.AddEntityResponse], error)
	// Update an entity in the scene.
	UpdateEntity(context.Context, *connect.Request[v1.UpdateEntityRequest]) (*connect.Response[v1.UpdateEntityResponse], error)
	// Remove an entity from the scene.
	RemoveEntity(context.Context, *connect.Request[v1.RemoveEntityRequest]) (*connect.Response[v1.RemoveEntityResponse], error)
	// Stream changes to entities in the scene.
	StreamEntityChanges(context.Context, *connect.Request[v1.StreamEntityChangesRequest], *connect.ServerStream[v1.StreamEntityChangesResponse]) error
	// Set the camera and/or metadata for the scene.
	SetScene(context.Context, *connect.Request[v1.SetSceneRequest]) (*connect.Response[v1.SetSceneResponse], error)
	// Stream changes to the camera and/or metadata for the scene.
	StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest], *connect.ServerStream[v1.StreamSceneChangesResponse]) error
	// Remove all transforms from the scene.
	RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error)
	// Remove all drawings from the scene.
	RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error)
	// Remove all entities from the scene.
	RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error)
}

// NewDrawServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDrawServiceHandler(svc DrawServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	drawServiceMethods := v1.File_draw_v1_service_proto.Services().ByName("DrawService").Methods()
	drawServiceAddEntityHandler := connect.NewUnaryHandler(
		DrawServiceAddEntityProcedure,
		svc.AddEntity,
		connect.WithSchema(drawServiceMethods.ByName("AddEntity")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceUpdateEntityHandler := connect.NewUnaryHandler(
		DrawServiceUpdateEntityProcedure,
		svc.UpdateEntity,
		connect.WithSchema(drawServiceMethods.ByName("UpdateEntity")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveEntityHandler := connect.NewUnaryHandler(
		DrawServiceRemoveEntityProcedure,
		svc.RemoveEntity,
		connect.WithSchema(drawServiceMethods.ByName("RemoveEntity")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceStreamEntityChangesHandler := connect.NewServerStreamHandler(
		DrawServiceStreamEntityChangesProcedure,
		svc.StreamEntityChanges,
		connect.WithSchema(drawServiceMethods.ByName("StreamEntityChanges")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceSetSceneHandler := connect.NewUnaryHandler(
		DrawServiceSetSceneProcedure,
		svc.SetScene,
		connect.WithSchema(drawServiceMethods.ByName("SetScene")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceStreamSceneChangesHandler := connect.NewServerStreamHandler(
		DrawServiceStreamSceneChangesProcedure,
		svc.StreamSceneChanges,
		connect.WithSchema(drawServiceMethods.ByName("StreamSceneChanges")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllTransformsHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllTransformsProcedure,
		svc.RemoveAllTransforms,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAllTransforms")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllDrawingsHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllDrawingsProcedure,
		svc.RemoveAllDrawings,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAllDrawings")),
		connect.WithHandlerOptions(opts...),
	)
	drawServiceRemoveAllHandler := connect.NewUnaryHandler(
		DrawServiceRemoveAllProcedure,
		svc.RemoveAll,
		connect.WithSchema(drawServiceMethods.ByName("RemoveAll")),
		connect.WithHandlerOptions(opts...),
	)
	return "/draw.v1.DrawService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DrawServiceAddEntityProcedure:
			drawServiceAddEntityHandler.ServeHTTP(w, r)
		case DrawServiceUpdateEntityProcedure:
			drawServiceUpdateEntityHandler.ServeHTTP(w, r)
		case DrawServiceRemoveEntityProcedure:
			drawServiceRemoveEntityHandler.ServeHTTP(w, r)
		case DrawServiceStreamEntityChangesProcedure:
			drawServiceStreamEntityChangesHandler.ServeHTTP(w, r)
		case DrawServiceSetSceneProcedure:
			drawServiceSetSceneHandler.ServeHTTP(w, r)
		case DrawServiceStreamSceneChangesProcedure:
			drawServiceStreamSceneChangesHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllTransformsProcedure:
			drawServiceRemoveAllTransformsHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllDrawingsProcedure:
			drawServiceRemoveAllDrawingsHandler.ServeHTTP(w, r)
		case DrawServiceRemoveAllProcedure:
			drawServiceRemoveAllHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDrawServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDrawServiceHandler struct{}

func (UnimplementedDrawServiceHandler) AddEntity(context.Context, *connect.Request[v1.AddEntityRequest]) (*connect.Response[v1.AddEntityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.AddEntity is not implemented"))
}

func (UnimplementedDrawServiceHandler) UpdateEntity(context.Context, *connect.Request[v1.UpdateEntityRequest]) (*connect.Response[v1.UpdateEntityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.UpdateEntity is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveEntity(context.Context, *connect.Request[v1.RemoveEntityRequest]) (*connect.Response[v1.RemoveEntityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveEntity is not implemented"))
}

func (UnimplementedDrawServiceHandler) StreamEntityChanges(context.Context, *connect.Request[v1.StreamEntityChangesRequest], *connect.ServerStream[v1.StreamEntityChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.StreamEntityChanges is not implemented"))
}

func (UnimplementedDrawServiceHandler) SetScene(context.Context, *connect.Request[v1.SetSceneRequest]) (*connect.Response[v1.SetSceneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.SetScene is not implemented"))
}

func (UnimplementedDrawServiceHandler) StreamSceneChanges(context.Context, *connect.Request[v1.StreamSceneChangesRequest], *connect.ServerStream[v1.StreamSceneChangesResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.StreamSceneChanges is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAllTransforms(context.Context, *connect.Request[v1.RemoveAllTransformsRequest]) (*connect.Response[v1.RemoveAllTransformsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAllTransforms is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAllDrawings(context.Context, *connect.Request[v1.RemoveAllDrawingsRequest]) (*connect.Response[v1.RemoveAllDrawingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAllDrawings is not implemented"))
}

func (UnimplementedDrawServiceHandler) RemoveAll(context.Context, *connect.Request[v1.RemoveAllRequest]) (*connect.Response[v1.RemoveAllResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("draw.v1.DrawService.RemoveAll is not implemented"))
}
