export { provideWorld, useWorld } from './useWorld'
export { useQuery, useTag, useTarget, useTrait } from 'koota/svelte'
export { useParentName } from './useParentName.svelte'
export { provideHierarchy } from './provideHierarchy.svelte'
export { provideWorldMatrix } from './provideWorldMatrix.svelte'
export { setOrAddTrait } from './setOrAddTrait'
export { selectOnly } from './selectOnly'

export * as traits from './traits'
export * as relations from './relations'
export * as hierarchy from './hierarchy'
