// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/drawing.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arrows represents a set of arrows in 3D space
// Metadata:
//   - colors: []uint8 of a single color or a color per arrow
//     defaults to [0, 128, 0] (green)
//   - color format: the format of the colors field, defaults to COLOR_FORMAT_RGB
//   - opacities: []uint8 of a single opacity or a opacity per arrow
//     defaults to [255] (fully opaque)
type Arrows struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The poses of the arrows
	// float32 array of poses: [x, y, z, ox, oy, oz]
	Poses         []byte `protobuf:"bytes,1,opt,name=poses,proto3" json:"poses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arrows) Reset() {
	*x = Arrows{}
	mi := &file_draw_v1_drawing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arrows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arrows) ProtoMessage() {}

func (x *Arrows) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arrows.ProtoReflect.Descriptor instead.
func (*Arrows) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{0}
}

func (x *Arrows) GetPoses() []byte {
	if x != nil {
		return x.Poses
	}
	return nil
}

// Line represents a line in 3D space
// Metadata:
//   - colors: []uint8 of a single color or a color per line point
//     defaults to [0, 0, 255] (blue)
//   - color format: the format of the colors field, defaults to COLOR_FORMAT_RGB
//   - opacities: []uint8 of a single opacity or a opacity per line point
//     defaults to [255] (fully opaque)
type Line struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The positions of the line dots
	// float32 array of positions: [x, y, z, ...]
	Positions []byte `protobuf:"bytes,1,opt,name=positions,proto3" json:"positions,omitempty"`
	// optional width of the line in millimeters, defaults to 5
	LineWidth *float32 `protobuf:"fixed32,2,opt,name=line_width,json=lineWidth,proto3,oneof" json:"line_width,omitempty"`
	// optional size of the dots in millimeters, defaults to 10
	DotSize *float32 `protobuf:"fixed32,3,opt,name=dot_size,json=dotSize,proto3,oneof" json:"dot_size,omitempty"`
	// optional colors for the line dots
	// []uint8 of a single color: [r, g, b, a]
	// or one color per dot: [r, g, b, a, ...]
	DotColors     []byte `protobuf:"bytes,4,opt,name=dot_colors,json=dotColors,proto3,oneof" json:"dot_colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_draw_v1_drawing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{1}
}

func (x *Line) GetPositions() []byte {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Line) GetLineWidth() float32 {
	if x != nil && x.LineWidth != nil {
		return *x.LineWidth
	}
	return 0
}

func (x *Line) GetDotSize() float32 {
	if x != nil && x.DotSize != nil {
		return *x.DotSize
	}
	return 0
}

func (x *Line) GetDotColors() []byte {
	if x != nil {
		return x.DotColors
	}
	return nil
}

// Points represents a set of points in 3D space
// Metadata:
//   - colors: []uint8 of a single color or a color per point
//     defaults to [128, 128, 128] (gray)
//   - color format: the format of the colors field, defaults to COLOR_FORMAT_RGB
//   - opacities: []uint8 of a single opacity or a opacity per point
//     defaults to [255] (fully opaque)
type Points struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The positions of the points
	// float32 array of positions: [x, y, z, ...]
	Positions []byte `protobuf:"bytes,1,opt,name=positions,proto3" json:"positions,omitempty"`
	// Size of the points in millimeters, defaults to 10
	PointSize     *float32 `protobuf:"fixed32,2,opt,name=point_size,json=pointSize,proto3,oneof" json:"point_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Points) Reset() {
	*x = Points{}
	mi := &file_draw_v1_drawing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Points) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Points) ProtoMessage() {}

func (x *Points) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Points.ProtoReflect.Descriptor instead.
func (*Points) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{2}
}

func (x *Points) GetPositions() []byte {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Points) GetPointSize() float32 {
	if x != nil && x.PointSize != nil {
		return *x.PointSize
	}
	return 0
}

// ModelAsset represents the type of model
type ModelAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mime type of the model asset
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Expected file size in bytes (helpful for progress tracking)
	SizeBytes *uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3,oneof" json:"size_bytes,omitempty"`
	// The content of the model asset
	//
	// Types that are valid to be assigned to Content:
	//
	//	*ModelAsset_Url
	//	*ModelAsset_Data
	Content       isModelAsset_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelAsset) Reset() {
	*x = ModelAsset{}
	mi := &file_draw_v1_drawing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelAsset) ProtoMessage() {}

func (x *ModelAsset) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelAsset.ProtoReflect.Descriptor instead.
func (*ModelAsset) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{3}
}

func (x *ModelAsset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ModelAsset) GetSizeBytes() uint64 {
	if x != nil && x.SizeBytes != nil {
		return *x.SizeBytes
	}
	return 0
}

func (x *ModelAsset) GetContent() isModelAsset_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ModelAsset) GetUrl() string {
	if x != nil {
		if x, ok := x.Content.(*ModelAsset_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *ModelAsset) GetData() []byte {
	if x != nil {
		if x, ok := x.Content.(*ModelAsset_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isModelAsset_Content interface {
	isModelAsset_Content()
}

type ModelAsset_Url struct {
	// The url of the model asset
	Url string `protobuf:"bytes,3,opt,name=url,proto3,oneof"`
}

type ModelAsset_Data struct {
	// The binary data of the model asset
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

func (*ModelAsset_Url) isModelAsset_Content() {}

func (*ModelAsset_Data) isModelAsset_Content() {}

// Model represents a 3D model in various formats
// Metadata:
// - colors: []uint8 of no colors
type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of assets that make up the model
	Assets []*ModelAsset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	// Uniform scale factor, defaults to [1.0, 1.0, 1.0]
	Scale *v1.Vector3 `protobuf:"bytes,2,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	// Name ofI the animation to play, defaults to empty string (no animation)
	AnimationName *string `protobuf:"bytes,3,opt,name=animation_name,json=animationName,proto3,oneof" json:"animation_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_draw_v1_drawing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{4}
}

func (x *Model) GetAssets() []*ModelAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *Model) GetScale() *v1.Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *Model) GetAnimationName() string {
	if x != nil && x.AnimationName != nil {
		return *x.AnimationName
	}
	return ""
}

// Nurbs represents a NURBS curve in 3D space
// Metadata:
//   - colors: []uint8 of a single color or a color per NURBS control point
//     defaults to [0, 255, 255] (cyan)
//   - color format: the format of the colors field, defaults to COLOR_FORMAT_RGB
//   - opacities: []uint8 of a single opacity or a opacity per NURBS control point
//     defaults to [255] (fully opaque)
type Nurbs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The control points of the NURBS
	// []float32 of poses: [x, y, z, ox, oy, oz, theta, ...]
	ControlPoints []byte `protobuf:"bytes,1,opt,name=control_points,json=controlPoints,proto3" json:"control_points,omitempty"`
	// The knots of the NURBS
	// float32 array of knots: [knot, ...]
	Knots []byte `protobuf:"bytes,2,opt,name=knots,proto3" json:"knots,omitempty"`
	// The degree of the NURBS, defaults to 3
	Degree *int32 `protobuf:"varint,3,opt,name=degree,proto3,oneof" json:"degree,omitempty"`
	// The weights of the NURBS, defaults to [1, 1, 1, ...]
	// float32 array of weights: [weight, ...]
	Weights []byte `protobuf:"bytes,4,opt,name=weights,proto3,oneof" json:"weights,omitempty"`
	// optional width of the line in millimeters, defaults to 5
	LineWidth     *float32 `protobuf:"fixed32,5,opt,name=line_width,json=lineWidth,proto3,oneof" json:"line_width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nurbs) Reset() {
	*x = Nurbs{}
	mi := &file_draw_v1_drawing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nurbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nurbs) ProtoMessage() {}

func (x *Nurbs) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nurbs.ProtoReflect.Descriptor instead.
func (*Nurbs) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{5}
}

func (x *Nurbs) GetControlPoints() []byte {
	if x != nil {
		return x.ControlPoints
	}
	return nil
}

func (x *Nurbs) GetKnots() []byte {
	if x != nil {
		return x.Knots
	}
	return nil
}

func (x *Nurbs) GetDegree() int32 {
	if x != nil && x.Degree != nil {
		return *x.Degree
	}
	return 0
}

func (x *Nurbs) GetWeights() []byte {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Nurbs) GetLineWidth() float32 {
	if x != nil && x.LineWidth != nil {
		return *x.LineWidth
	}
	return 0
}

type Shape struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The center of the shape
	Center *v1.Pose `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	// The label of the shape
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// The type of the shape
	//
	// Types that are valid to be assigned to GeometryType:
	//
	//	*Shape_Arrows
	//	*Shape_Line
	//	*Shape_Points
	//	*Shape_Model
	//	*Shape_Nurbs
	GeometryType  isShape_GeometryType `protobuf_oneof:"geometry_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shape) Reset() {
	*x = Shape{}
	mi := &file_draw_v1_drawing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{6}
}

func (x *Shape) GetCenter() *v1.Pose {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Shape) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Shape) GetGeometryType() isShape_GeometryType {
	if x != nil {
		return x.GeometryType
	}
	return nil
}

func (x *Shape) GetArrows() *Arrows {
	if x != nil {
		if x, ok := x.GeometryType.(*Shape_Arrows); ok {
			return x.Arrows
		}
	}
	return nil
}

func (x *Shape) GetLine() *Line {
	if x != nil {
		if x, ok := x.GeometryType.(*Shape_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *Shape) GetPoints() *Points {
	if x != nil {
		if x, ok := x.GeometryType.(*Shape_Points); ok {
			return x.Points
		}
	}
	return nil
}

func (x *Shape) GetModel() *Model {
	if x != nil {
		if x, ok := x.GeometryType.(*Shape_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *Shape) GetNurbs() *Nurbs {
	if x != nil {
		if x, ok := x.GeometryType.(*Shape_Nurbs); ok {
			return x.Nurbs
		}
	}
	return nil
}

type isShape_GeometryType interface {
	isShape_GeometryType()
}

type Shape_Arrows struct {
	Arrows *Arrows `protobuf:"bytes,3,opt,name=arrows,proto3,oneof"`
}

type Shape_Line struct {
	Line *Line `protobuf:"bytes,4,opt,name=line,proto3,oneof"`
}

type Shape_Points struct {
	Points *Points `protobuf:"bytes,5,opt,name=points,proto3,oneof"`
}

type Shape_Model struct {
	Model *Model `protobuf:"bytes,6,opt,name=model,proto3,oneof"`
}

type Shape_Nurbs struct {
	Nurbs *Nurbs `protobuf:"bytes,7,opt,name=nurbs,proto3,oneof"`
}

func (*Shape_Arrows) isShape_GeometryType() {}

func (*Shape_Line) isShape_GeometryType() {}

func (*Shape_Points) isShape_GeometryType() {}

func (*Shape_Model) isShape_GeometryType() {}

func (*Shape_Nurbs) isShape_GeometryType() {}

// For non-physical visualization shapes
type Drawing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the shape
	ReferenceFrame string `protobuf:"bytes,1,opt,name=reference_frame,json=referenceFrame,proto3" json:"reference_frame,omitempty"`
	// The pose of the shape as observed through it's parent frame/the world
	PoseInObserverFrame *v1.PoseInFrame `protobuf:"bytes,2,opt,name=pose_in_observer_frame,json=poseInObserverFrame,proto3" json:"pose_in_observer_frame,omitempty"`
	// The shape of the drawing
	PhysicalObject *Shape `protobuf:"bytes,3,opt,name=physical_object,json=physicalObject,proto3,oneof" json:"physical_object,omitempty"`
	// The UUID of the shape
	Uuid []byte `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The metadata of the shape
	Metadata      *Metadata `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drawing) Reset() {
	*x = Drawing{}
	mi := &file_draw_v1_drawing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drawing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drawing) ProtoMessage() {}

func (x *Drawing) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_drawing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drawing.ProtoReflect.Descriptor instead.
func (*Drawing) Descriptor() ([]byte, []int) {
	return file_draw_v1_drawing_proto_rawDescGZIP(), []int{7}
}

func (x *Drawing) GetReferenceFrame() string {
	if x != nil {
		return x.ReferenceFrame
	}
	return ""
}

func (x *Drawing) GetPoseInObserverFrame() *v1.PoseInFrame {
	if x != nil {
		return x.PoseInObserverFrame
	}
	return nil
}

func (x *Drawing) GetPhysicalObject() *Shape {
	if x != nil {
		return x.PhysicalObject
	}
	return nil
}

func (x *Drawing) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Drawing) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_draw_v1_drawing_proto protoreflect.FileDescriptor

const file_draw_v1_drawing_proto_rawDesc = "" +
	"\n" +
	"\x15draw/v1/drawing.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\x1a\x16draw/v1/metadata.proto\"\x1e\n" +
	"\x06Arrows\x12\x14\n" +
	"\x05poses\x18\x01 \x01(\fR\x05poses\"\xb7\x01\n" +
	"\x04Line\x12\x1c\n" +
	"\tpositions\x18\x01 \x01(\fR\tpositions\x12\"\n" +
	"\n" +
	"line_width\x18\x02 \x01(\x02H\x00R\tlineWidth\x88\x01\x01\x12\x1e\n" +
	"\bdot_size\x18\x03 \x01(\x02H\x01R\adotSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"dot_colors\x18\x04 \x01(\fH\x02R\tdotColors\x88\x01\x01B\r\n" +
	"\v_line_widthB\v\n" +
	"\t_dot_sizeB\r\n" +
	"\v_dot_colors\"Y\n" +
	"\x06Points\x12\x1c\n" +
	"\tpositions\x18\x01 \x01(\fR\tpositions\x12\"\n" +
	"\n" +
	"point_size\x18\x02 \x01(\x02H\x00R\tpointSize\x88\x01\x01B\r\n" +
	"\v_point_size\"\x91\x01\n" +
	"\n" +
	"ModelAsset\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\"\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04H\x01R\tsizeBytes\x88\x01\x01\x12\x12\n" +
	"\x03url\x18\x03 \x01(\tH\x00R\x03url\x12\x14\n" +
	"\x04data\x18\x04 \x01(\fH\x00R\x04dataB\t\n" +
	"\acontentB\r\n" +
	"\v_size_bytes\"\xb1\x01\n" +
	"\x05Model\x12+\n" +
	"\x06assets\x18\x01 \x03(\v2\x13.draw.v1.ModelAssetR\x06assets\x122\n" +
	"\x05scale\x18\x02 \x01(\v2\x17.viam.common.v1.Vector3H\x00R\x05scale\x88\x01\x01\x12*\n" +
	"\x0eanimation_name\x18\x03 \x01(\tH\x01R\ranimationName\x88\x01\x01B\b\n" +
	"\x06_scaleB\x11\n" +
	"\x0f_animation_name\"\xca\x01\n" +
	"\x05Nurbs\x12%\n" +
	"\x0econtrol_points\x18\x01 \x01(\fR\rcontrolPoints\x12\x14\n" +
	"\x05knots\x18\x02 \x01(\fR\x05knots\x12\x1b\n" +
	"\x06degree\x18\x03 \x01(\x05H\x00R\x06degree\x88\x01\x01\x12\x1d\n" +
	"\aweights\x18\x04 \x01(\fH\x01R\aweights\x88\x01\x01\x12\"\n" +
	"\n" +
	"line_width\x18\x05 \x01(\x02H\x02R\tlineWidth\x88\x01\x01B\t\n" +
	"\a_degreeB\n" +
	"\n" +
	"\b_weightsB\r\n" +
	"\v_line_width\"\xa7\x02\n" +
	"\x05Shape\x12,\n" +
	"\x06center\x18\x01 \x01(\v2\x14.viam.common.v1.PoseR\x06center\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12)\n" +
	"\x06arrows\x18\x03 \x01(\v2\x0f.draw.v1.ArrowsH\x00R\x06arrows\x12#\n" +
	"\x04line\x18\x04 \x01(\v2\r.draw.v1.LineH\x00R\x04line\x12)\n" +
	"\x06points\x18\x05 \x01(\v2\x0f.draw.v1.PointsH\x00R\x06points\x12&\n" +
	"\x05model\x18\x06 \x01(\v2\x0e.draw.v1.ModelH\x00R\x05model\x12&\n" +
	"\x05nurbs\x18\a \x01(\v2\x0e.draw.v1.NurbsH\x00R\x05nurbsB\x0f\n" +
	"\rgeometry_type\"\xab\x02\n" +
	"\aDrawing\x12'\n" +
	"\x0freference_frame\x18\x01 \x01(\tR\x0ereferenceFrame\x12P\n" +
	"\x16pose_in_observer_frame\x18\x02 \x01(\v2\x1b.viam.common.v1.PoseInFrameR\x13poseInObserverFrame\x12<\n" +
	"\x0fphysical_object\x18\x03 \x01(\v2\x0e.draw.v1.ShapeH\x00R\x0ephysicalObject\x88\x01\x01\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\fR\x04uuid\x122\n" +
	"\bmetadata\x18\x05 \x01(\v2\x11.draw.v1.MetadataH\x01R\bmetadata\x88\x01\x01B\x12\n" +
	"\x10_physical_objectB\v\n" +
	"\t_metadataB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_drawing_proto_rawDescOnce sync.Once
	file_draw_v1_drawing_proto_rawDescData []byte
)

func file_draw_v1_drawing_proto_rawDescGZIP() []byte {
	file_draw_v1_drawing_proto_rawDescOnce.Do(func() {
		file_draw_v1_drawing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_drawing_proto_rawDesc), len(file_draw_v1_drawing_proto_rawDesc)))
	})
	return file_draw_v1_drawing_proto_rawDescData
}

var file_draw_v1_drawing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_draw_v1_drawing_proto_goTypes = []any{
	(*Arrows)(nil),         // 0: draw.v1.Arrows
	(*Line)(nil),           // 1: draw.v1.Line
	(*Points)(nil),         // 2: draw.v1.Points
	(*ModelAsset)(nil),     // 3: draw.v1.ModelAsset
	(*Model)(nil),          // 4: draw.v1.Model
	(*Nurbs)(nil),          // 5: draw.v1.Nurbs
	(*Shape)(nil),          // 6: draw.v1.Shape
	(*Drawing)(nil),        // 7: draw.v1.Drawing
	(*v1.Vector3)(nil),     // 8: viam.common.v1.Vector3
	(*v1.Pose)(nil),        // 9: viam.common.v1.Pose
	(*v1.PoseInFrame)(nil), // 10: viam.common.v1.PoseInFrame
	(*Metadata)(nil),       // 11: draw.v1.Metadata
}
var file_draw_v1_drawing_proto_depIdxs = []int32{
	3,  // 0: draw.v1.Model.assets:type_name -> draw.v1.ModelAsset
	8,  // 1: draw.v1.Model.scale:type_name -> viam.common.v1.Vector3
	9,  // 2: draw.v1.Shape.center:type_name -> viam.common.v1.Pose
	0,  // 3: draw.v1.Shape.arrows:type_name -> draw.v1.Arrows
	1,  // 4: draw.v1.Shape.line:type_name -> draw.v1.Line
	2,  // 5: draw.v1.Shape.points:type_name -> draw.v1.Points
	4,  // 6: draw.v1.Shape.model:type_name -> draw.v1.Model
	5,  // 7: draw.v1.Shape.nurbs:type_name -> draw.v1.Nurbs
	10, // 8: draw.v1.Drawing.pose_in_observer_frame:type_name -> viam.common.v1.PoseInFrame
	6,  // 9: draw.v1.Drawing.physical_object:type_name -> draw.v1.Shape
	11, // 10: draw.v1.Drawing.metadata:type_name -> draw.v1.Metadata
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_draw_v1_drawing_proto_init() }
func file_draw_v1_drawing_proto_init() {
	if File_draw_v1_drawing_proto != nil {
		return
	}
	file_draw_v1_metadata_proto_init()
	file_draw_v1_drawing_proto_msgTypes[1].OneofWrappers = []any{}
	file_draw_v1_drawing_proto_msgTypes[2].OneofWrappers = []any{}
	file_draw_v1_drawing_proto_msgTypes[3].OneofWrappers = []any{
		(*ModelAsset_Url)(nil),
		(*ModelAsset_Data)(nil),
	}
	file_draw_v1_drawing_proto_msgTypes[4].OneofWrappers = []any{}
	file_draw_v1_drawing_proto_msgTypes[5].OneofWrappers = []any{}
	file_draw_v1_drawing_proto_msgTypes[6].OneofWrappers = []any{
		(*Shape_Arrows)(nil),
		(*Shape_Line)(nil),
		(*Shape_Points)(nil),
		(*Shape_Model)(nil),
		(*Shape_Nurbs)(nil),
	}
	file_draw_v1_drawing_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_drawing_proto_rawDesc), len(file_draw_v1_drawing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_drawing_proto_goTypes,
		DependencyIndexes: file_draw_v1_drawing_proto_depIdxs,
		MessageInfos:      file_draw_v1_drawing_proto_msgTypes,
	}.Build()
	File_draw_v1_drawing_proto = out.File
	file_draw_v1_drawing_proto_goTypes = nil
	file_draw_v1_drawing_proto_depIdxs = nil
}
