// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/metadata.proto

package drawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uint8Array of colors: [r, g, b, a, ...]
	// For simple objects, this is a single color of [r, g, b, a]
	// For complex objects, this is an array of colors of [r, g, b, a, ...]
	Colors        []byte `protobuf:"bytes,1,opt,name=colors,proto3,oneof" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_draw_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_draw_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetColors() []byte {
	if x != nil {
		return x.Colors
	}
	return nil
}

var File_draw_v1_metadata_proto protoreflect.FileDescriptor

const file_draw_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x16draw/v1/metadata.proto\x12\adraw.v1\"2\n" +
	"\bMetadata\x12\x1b\n" +
	"\x06colors\x18\x01 \x01(\fH\x00R\x06colors\x88\x01\x01B\t\n" +
	"\a_colorsB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_metadata_proto_rawDescOnce sync.Once
	file_draw_v1_metadata_proto_rawDescData []byte
)

func file_draw_v1_metadata_proto_rawDescGZIP() []byte {
	file_draw_v1_metadata_proto_rawDescOnce.Do(func() {
		file_draw_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_metadata_proto_rawDesc), len(file_draw_v1_metadata_proto_rawDesc)))
	})
	return file_draw_v1_metadata_proto_rawDescData
}

var file_draw_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_draw_v1_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: draw.v1.Metadata
}
var file_draw_v1_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_draw_v1_metadata_proto_init() }
func file_draw_v1_metadata_proto_init() {
	if File_draw_v1_metadata_proto != nil {
		return
	}
	file_draw_v1_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_metadata_proto_rawDesc), len(file_draw_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_metadata_proto_goTypes,
		DependencyIndexes: file_draw_v1_metadata_proto_depIdxs,
		MessageInfos:      file_draw_v1_metadata_proto_msgTypes,
	}.Build()
	File_draw_v1_metadata_proto = out.File
	file_draw_v1_metadata_proto_goTypes = nil
	file_draw_v1_metadata_proto_depIdxs = nil
}
