// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/metadata.proto

package drawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColorFormat describes the encoding of the colors bytes field.
type ColorFormat int32

const (
	ColorFormat_COLOR_FORMAT_UNSPECIFIED ColorFormat = 0
	ColorFormat_COLOR_FORMAT_RGB         ColorFormat = 1
)

// Enum value maps for ColorFormat.
var (
	ColorFormat_name = map[int32]string{
		0: "COLOR_FORMAT_UNSPECIFIED",
		1: "COLOR_FORMAT_RGB",
	}
	ColorFormat_value = map[string]int32{
		"COLOR_FORMAT_UNSPECIFIED": 0,
		"COLOR_FORMAT_RGB":         1,
	}
)

func (x ColorFormat) Enum() *ColorFormat {
	p := new(ColorFormat)
	*p = x
	return p
}

func (x ColorFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_metadata_proto_enumTypes[0].Descriptor()
}

func (ColorFormat) Type() protoreflect.EnumType {
	return &file_draw_v1_metadata_proto_enumTypes[0]
}

func (x ColorFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorFormat.Descriptor instead.
func (ColorFormat) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_metadata_proto_rawDescGZIP(), []int{0}
}

// Chunks describes how a large entity is chunked for progressive delivery.
type Chunks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of elements per chunk.
	ChunkSize uint32 `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// The total number of elements across all chunks.
	Total uint32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// The number of bytes per element (e.g. 12 for float32 xyz positions).
	Stride        uint32 `protobuf:"varint,3,opt,name=stride,proto3" json:"stride,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunks) Reset() {
	*x = Chunks{}
	mi := &file_draw_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunks) ProtoMessage() {}

func (x *Chunks) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunks.ProtoReflect.Descriptor instead.
func (*Chunks) Descriptor() ([]byte, []int) {
	return file_draw_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Chunks) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *Chunks) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Chunks) GetStride() uint32 {
	if x != nil {
		return x.Stride
	}
	return 0
}

type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uint8Array of color values (0-255) based on the color format.
	// Can be a single set of values for a uniform color, or an array of values for per-vertex colors.
	Colors []byte `protobuf:"bytes,1,opt,name=colors,proto3,oneof" json:"colors,omitempty"`
	// Describes the encoding of the colors field. Defaults to COLOR_FORMAT_RGB when set by this API.
	ColorFormat ColorFormat `protobuf:"varint,2,opt,name=color_format,json=colorFormat,proto3,enum=draw.v1.ColorFormat" json:"color_format,omitempty"`
	// Uint8Array of opacity values (0-255) corresponding to colors.
	// Can be a single set of values for a uniform opacity, or an array of values for per-vertex opacity.
	Opacities []byte `protobuf:"bytes,3,opt,name=opacities,proto3,oneof" json:"opacities,omitempty"`
	// Whether to show the axes helper (RGB XYZ indicator) on the entity.
	// Defaults to false.
	ShowAxesHelper *bool `protobuf:"varint,4,opt,name=show_axes_helper,json=showAxesHelper,proto3,oneof" json:"show_axes_helper,omitempty"`
	// Whether the entity is invisible (not rendered) by default.
	// Defaults to false.
	Invisible *bool `protobuf:"varint,5,opt,name=invisible,proto3,oneof" json:"invisible,omitempty"`
	// When present, indicates this drawing uses chunked delivery.
	Chunks        *Chunks `protobuf:"bytes,6,opt,name=chunks,proto3,oneof" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_draw_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_draw_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetColors() []byte {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Metadata) GetColorFormat() ColorFormat {
	if x != nil {
		return x.ColorFormat
	}
	return ColorFormat_COLOR_FORMAT_UNSPECIFIED
}

func (x *Metadata) GetOpacities() []byte {
	if x != nil {
		return x.Opacities
	}
	return nil
}

func (x *Metadata) GetShowAxesHelper() bool {
	if x != nil && x.ShowAxesHelper != nil {
		return *x.ShowAxesHelper
	}
	return false
}

func (x *Metadata) GetInvisible() bool {
	if x != nil && x.Invisible != nil {
		return *x.Invisible
	}
	return false
}

func (x *Metadata) GetChunks() *Chunks {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_draw_v1_metadata_proto protoreflect.FileDescriptor

const file_draw_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x16draw/v1/metadata.proto\x12\adraw.v1\"U\n" +
	"\x06Chunks\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\rR\tchunkSize\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x16\n" +
	"\x06stride\x18\x03 \x01(\rR\x06stride\"\xca\x02\n" +
	"\bMetadata\x12\x1b\n" +
	"\x06colors\x18\x01 \x01(\fH\x00R\x06colors\x88\x01\x01\x127\n" +
	"\fcolor_format\x18\x02 \x01(\x0e2\x14.draw.v1.ColorFormatR\vcolorFormat\x12!\n" +
	"\topacities\x18\x03 \x01(\fH\x01R\topacities\x88\x01\x01\x12-\n" +
	"\x10show_axes_helper\x18\x04 \x01(\bH\x02R\x0eshowAxesHelper\x88\x01\x01\x12!\n" +
	"\tinvisible\x18\x05 \x01(\bH\x03R\tinvisible\x88\x01\x01\x12,\n" +
	"\x06chunks\x18\x06 \x01(\v2\x0f.draw.v1.ChunksH\x04R\x06chunks\x88\x01\x01B\t\n" +
	"\a_colorsB\f\n" +
	"\n" +
	"_opacitiesB\x13\n" +
	"\x11_show_axes_helperB\f\n" +
	"\n" +
	"_invisibleB\t\n" +
	"\a_chunks*A\n" +
	"\vColorFormat\x12\x1c\n" +
	"\x18COLOR_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COLOR_FORMAT_RGB\x10\x01B2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_metadata_proto_rawDescOnce sync.Once
	file_draw_v1_metadata_proto_rawDescData []byte
)

func file_draw_v1_metadata_proto_rawDescGZIP() []byte {
	file_draw_v1_metadata_proto_rawDescOnce.Do(func() {
		file_draw_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_metadata_proto_rawDesc), len(file_draw_v1_metadata_proto_rawDesc)))
	})
	return file_draw_v1_metadata_proto_rawDescData
}

var file_draw_v1_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_draw_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_draw_v1_metadata_proto_goTypes = []any{
	(ColorFormat)(0), // 0: draw.v1.ColorFormat
	(*Chunks)(nil),   // 1: draw.v1.Chunks
	(*Metadata)(nil), // 2: draw.v1.Metadata
}
var file_draw_v1_metadata_proto_depIdxs = []int32{
	0, // 0: draw.v1.Metadata.color_format:type_name -> draw.v1.ColorFormat
	1, // 1: draw.v1.Metadata.chunks:type_name -> draw.v1.Chunks
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_draw_v1_metadata_proto_init() }
func file_draw_v1_metadata_proto_init() {
	if File_draw_v1_metadata_proto != nil {
		return
	}
	file_draw_v1_metadata_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_metadata_proto_rawDesc), len(file_draw_v1_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_metadata_proto_goTypes,
		DependencyIndexes: file_draw_v1_metadata_proto_depIdxs,
		EnumInfos:         file_draw_v1_metadata_proto_enumTypes,
		MessageInfos:      file_draw_v1_metadata_proto_msgTypes,
	}.Build()
	File_draw_v1_metadata_proto = out.File
	file_draw_v1_metadata_proto_goTypes = nil
	file_draw_v1_metadata_proto_depIdxs = nil
}
