// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/scene.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderArmModels int32

const (
	RenderArmModels_RENDER_ARM_MODELS_UNSPECIFIED         RenderArmModels = 0
	RenderArmModels_RENDER_ARM_MODELS_COLLIDERS           RenderArmModels = 1
	RenderArmModels_RENDER_ARM_MODELS_COLLIDERS_AND_MODEL RenderArmModels = 2
	RenderArmModels_RENDER_ARM_MODELS_MODEL               RenderArmModels = 3
)

// Enum value maps for RenderArmModels.
var (
	RenderArmModels_name = map[int32]string{
		0: "RENDER_ARM_MODELS_UNSPECIFIED",
		1: "RENDER_ARM_MODELS_COLLIDERS",
		2: "RENDER_ARM_MODELS_COLLIDERS_AND_MODEL",
		3: "RENDER_ARM_MODELS_MODEL",
	}
	RenderArmModels_value = map[string]int32{
		"RENDER_ARM_MODELS_UNSPECIFIED":         0,
		"RENDER_ARM_MODELS_COLLIDERS":           1,
		"RENDER_ARM_MODELS_COLLIDERS_AND_MODEL": 2,
		"RENDER_ARM_MODELS_MODEL":               3,
	}
)

func (x RenderArmModels) Enum() *RenderArmModels {
	p := new(RenderArmModels)
	*p = x
	return p
}

func (x RenderArmModels) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderArmModels) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_scene_proto_enumTypes[0].Descriptor()
}

func (RenderArmModels) Type() protoreflect.EnumType {
	return &file_draw_v1_scene_proto_enumTypes[0]
}

func (x RenderArmModels) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderArmModels.Descriptor instead.
func (RenderArmModels) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{0}
}

type RenderShapes int32

const (
	RenderShapes_RENDER_SHAPES_UNSPECIFIED RenderShapes = 0
	RenderShapes_RENDER_SHAPES_ARROWS      RenderShapes = 1
	RenderShapes_RENDER_SHAPES_LINES       RenderShapes = 2
	RenderShapes_RENDER_SHAPES_POINTS      RenderShapes = 3
	RenderShapes_RENDER_SHAPES_MODEL       RenderShapes = 4
	RenderShapes_RENDER_SHAPES_NURBS       RenderShapes = 5
)

// Enum value maps for RenderShapes.
var (
	RenderShapes_name = map[int32]string{
		0: "RENDER_SHAPES_UNSPECIFIED",
		1: "RENDER_SHAPES_ARROWS",
		2: "RENDER_SHAPES_LINES",
		3: "RENDER_SHAPES_POINTS",
		4: "RENDER_SHAPES_MODEL",
		5: "RENDER_SHAPES_NURBS",
	}
	RenderShapes_value = map[string]int32{
		"RENDER_SHAPES_UNSPECIFIED": 0,
		"RENDER_SHAPES_ARROWS":      1,
		"RENDER_SHAPES_LINES":       2,
		"RENDER_SHAPES_POINTS":      3,
		"RENDER_SHAPES_MODEL":       4,
		"RENDER_SHAPES_NURBS":       5,
	}
)

func (x RenderShapes) Enum() *RenderShapes {
	p := new(RenderShapes)
	*p = x
	return p
}

func (x RenderShapes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderShapes) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_scene_proto_enumTypes[1].Descriptor()
}

func (RenderShapes) Type() protoreflect.EnumType {
	return &file_draw_v1_scene_proto_enumTypes[1]
}

func (x RenderShapes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderShapes.Descriptor instead.
func (RenderShapes) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{1}
}

type OrthographicCamera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zoom          *float32               `protobuf:"fixed32,1,opt,name=zoom,proto3,oneof" json:"zoom,omitempty"` // for orthographic camera props
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrthographicCamera) Reset() {
	*x = OrthographicCamera{}
	mi := &file_draw_v1_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrthographicCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrthographicCamera) ProtoMessage() {}

func (x *OrthographicCamera) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrthographicCamera.ProtoReflect.Descriptor instead.
func (*OrthographicCamera) Descriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{0}
}

func (x *OrthographicCamera) GetZoom() float32 {
	if x != nil && x.Zoom != nil {
		return *x.Zoom
	}
	return 0
}

type PerspectiveCamera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerspectiveCamera) Reset() {
	*x = PerspectiveCamera{}
	mi := &file_draw_v1_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerspectiveCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerspectiveCamera) ProtoMessage() {}

func (x *PerspectiveCamera) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerspectiveCamera.ProtoReflect.Descriptor instead.
func (*PerspectiveCamera) Descriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{1}
}

type SceneCamera struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The position of the camera in millimeters
	// defaults to [0, 0, 3000]
	Position *v1.Vector3 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// The look at point of the camera in millimeters
	// defaults to [0, 0, 0]
	LookAt *v1.Vector3 `protobuf:"bytes,2,opt,name=look_at,json=lookAt,proto3" json:"look_at,omitempty"`
	// Whether to animate camera movement
	// defaults to false
	Animated *bool `protobuf:"varint,3,opt,name=animated,proto3,oneof" json:"animated,omitempty"`
	// The camera type
	// defaults to perspective_camera
	//
	// Types that are valid to be assigned to CameraType:
	//
	//	*SceneCamera_PerspectiveCamera
	//	*SceneCamera_OrthographicCamera
	CameraType    isSceneCamera_CameraType `protobuf_oneof:"camera_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneCamera) Reset() {
	*x = SceneCamera{}
	mi := &file_draw_v1_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneCamera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCamera) ProtoMessage() {}

func (x *SceneCamera) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCamera.ProtoReflect.Descriptor instead.
func (*SceneCamera) Descriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{2}
}

func (x *SceneCamera) GetPosition() *v1.Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SceneCamera) GetLookAt() *v1.Vector3 {
	if x != nil {
		return x.LookAt
	}
	return nil
}

func (x *SceneCamera) GetAnimated() bool {
	if x != nil && x.Animated != nil {
		return *x.Animated
	}
	return false
}

func (x *SceneCamera) GetCameraType() isSceneCamera_CameraType {
	if x != nil {
		return x.CameraType
	}
	return nil
}

func (x *SceneCamera) GetPerspectiveCamera() *PerspectiveCamera {
	if x != nil {
		if x, ok := x.CameraType.(*SceneCamera_PerspectiveCamera); ok {
			return x.PerspectiveCamera
		}
	}
	return nil
}

func (x *SceneCamera) GetOrthographicCamera() *OrthographicCamera {
	if x != nil {
		if x, ok := x.CameraType.(*SceneCamera_OrthographicCamera); ok {
			return x.OrthographicCamera
		}
	}
	return nil
}

type isSceneCamera_CameraType interface {
	isSceneCamera_CameraType()
}

type SceneCamera_PerspectiveCamera struct {
	PerspectiveCamera *PerspectiveCamera `protobuf:"bytes,4,opt,name=perspective_camera,json=perspectiveCamera,proto3,oneof"`
}

type SceneCamera_OrthographicCamera struct {
	OrthographicCamera *OrthographicCamera `protobuf:"bytes,5,opt,name=orthographic_camera,json=orthographicCamera,proto3,oneof"`
}

func (*SceneCamera_PerspectiveCamera) isSceneCamera_CameraType() {}

func (*SceneCamera_OrthographicCamera) isSceneCamera_CameraType() {}

type SceneMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The camera to use for the scene
	// defaults to a perspective_camera with a position of [3000, 3000, 3000] and
	// a look_at of [0, 0, 0]
	SceneCamera *SceneCamera `protobuf:"bytes,1,opt,name=scene_camera,json=sceneCamera,proto3,oneof" json:"scene_camera,omitempty"`
	// Whether to render the grid
	// defaults to true
	Grid *bool `protobuf:"varint,2,opt,name=grid,proto3,oneof" json:"grid,omitempty"`
	// The size of the grid cells
	// defaults to 500 (millimeters)
	GridCellSize *float32 `protobuf:"fixed32,3,opt,name=grid_cell_size,json=gridCellSize,proto3,oneof" json:"grid_cell_size,omitempty"`
	// The size of the grid sections
	// defaults to 10000 (millimeters)
	GridSectionSize *float32 `protobuf:"fixed32,4,opt,name=grid_section_size,json=gridSectionSize,proto3,oneof" json:"grid_section_size,omitempty"`
	// The fade distance of the grid
	// defaults to 25000 (millimeters)
	GridFadeDistance *float32 `protobuf:"fixed32,5,opt,name=grid_fade_distance,json=gridFadeDistance,proto3,oneof" json:"grid_fade_distance,omitempty"`
	// The size of points if not defined by a transform's metadata
	// defaults to 10 (millimeters)
	PointSize *float32 `protobuf:"fixed32,6,opt,name=point_size,json=pointSize,proto3,oneof" json:"point_size,omitempty"`
	// The color of the points if not defined by a transform's metadata
	// defaults to [51, 51, 51, 255] (gray)
	PointColor []byte `protobuf:"bytes,7,opt,name=point_color,json=pointColor,proto3,oneof" json:"point_color,omitempty"`
	// The width of the lines if not defined by a transform's metadata
	// defaults to 5 (millimeters)
	LineWidth *float32 `protobuf:"fixed32,8,opt,name=line_width,json=lineWidth,proto3,oneof" json:"line_width,omitempty"`
	// The size of the points of the lines if not defined by a transform's
	// metadata defaults to 10 (millimeters)
	LinePointSize *float32 `protobuf:"fixed32,9,opt,name=line_point_size,json=linePointSize,proto3,oneof" json:"line_point_size,omitempty"`
	// The models to render
	// defaults to COLLIDERS_AND_MODEL
	RenderArmModels *RenderArmModels `protobuf:"varint,10,opt,name=render_arm_models,json=renderArmModels,proto3,enum=draw.v1.RenderArmModels,oneof" json:"render_arm_models,omitempty"`
	// The shapes to render
	// defaults to [ARROWS, POINTS, LINES, MODEL, NURBS]
	RenderShapes  []RenderShapes `protobuf:"varint,11,rep,packed,name=render_shapes,json=renderShapes,proto3,enum=draw.v1.RenderShapes" json:"render_shapes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneMetadata) Reset() {
	*x = SceneMetadata{}
	mi := &file_draw_v1_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneMetadata) ProtoMessage() {}

func (x *SceneMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneMetadata.ProtoReflect.Descriptor instead.
func (*SceneMetadata) Descriptor() ([]byte, []int) {
	return file_draw_v1_scene_proto_rawDescGZIP(), []int{3}
}

func (x *SceneMetadata) GetSceneCamera() *SceneCamera {
	if x != nil {
		return x.SceneCamera
	}
	return nil
}

func (x *SceneMetadata) GetGrid() bool {
	if x != nil && x.Grid != nil {
		return *x.Grid
	}
	return false
}

func (x *SceneMetadata) GetGridCellSize() float32 {
	if x != nil && x.GridCellSize != nil {
		return *x.GridCellSize
	}
	return 0
}

func (x *SceneMetadata) GetGridSectionSize() float32 {
	if x != nil && x.GridSectionSize != nil {
		return *x.GridSectionSize
	}
	return 0
}

func (x *SceneMetadata) GetGridFadeDistance() float32 {
	if x != nil && x.GridFadeDistance != nil {
		return *x.GridFadeDistance
	}
	return 0
}

func (x *SceneMetadata) GetPointSize() float32 {
	if x != nil && x.PointSize != nil {
		return *x.PointSize
	}
	return 0
}

func (x *SceneMetadata) GetPointColor() []byte {
	if x != nil {
		return x.PointColor
	}
	return nil
}

func (x *SceneMetadata) GetLineWidth() float32 {
	if x != nil && x.LineWidth != nil {
		return *x.LineWidth
	}
	return 0
}

func (x *SceneMetadata) GetLinePointSize() float32 {
	if x != nil && x.LinePointSize != nil {
		return *x.LinePointSize
	}
	return 0
}

func (x *SceneMetadata) GetRenderArmModels() RenderArmModels {
	if x != nil && x.RenderArmModels != nil {
		return *x.RenderArmModels
	}
	return RenderArmModels_RENDER_ARM_MODELS_UNSPECIFIED
}

func (x *SceneMetadata) GetRenderShapes() []RenderShapes {
	if x != nil {
		return x.RenderShapes
	}
	return nil
}

var File_draw_v1_scene_proto protoreflect.FileDescriptor

const file_draw_v1_scene_proto_rawDesc = "" +
	"\n" +
	"\x13draw/v1/scene.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\"6\n" +
	"\x12OrthographicCamera\x12\x17\n" +
	"\x04zoom\x18\x01 \x01(\x02H\x00R\x04zoom\x88\x01\x01B\a\n" +
	"\x05_zoom\"\x13\n" +
	"\x11PerspectiveCamera\"\xce\x02\n" +
	"\vSceneCamera\x123\n" +
	"\bposition\x18\x01 \x01(\v2\x17.viam.common.v1.Vector3R\bposition\x120\n" +
	"\alook_at\x18\x02 \x01(\v2\x17.viam.common.v1.Vector3R\x06lookAt\x12\x1f\n" +
	"\banimated\x18\x03 \x01(\bH\x01R\banimated\x88\x01\x01\x12K\n" +
	"\x12perspective_camera\x18\x04 \x01(\v2\x1a.draw.v1.PerspectiveCameraH\x00R\x11perspectiveCamera\x12N\n" +
	"\x13orthographic_camera\x18\x05 \x01(\v2\x1b.draw.v1.OrthographicCameraH\x00R\x12orthographicCameraB\r\n" +
	"\vcamera_typeB\v\n" +
	"\t_animated\"\xc9\x05\n" +
	"\rSceneMetadata\x12<\n" +
	"\fscene_camera\x18\x01 \x01(\v2\x14.draw.v1.SceneCameraH\x00R\vsceneCamera\x88\x01\x01\x12\x17\n" +
	"\x04grid\x18\x02 \x01(\bH\x01R\x04grid\x88\x01\x01\x12)\n" +
	"\x0egrid_cell_size\x18\x03 \x01(\x02H\x02R\fgridCellSize\x88\x01\x01\x12/\n" +
	"\x11grid_section_size\x18\x04 \x01(\x02H\x03R\x0fgridSectionSize\x88\x01\x01\x121\n" +
	"\x12grid_fade_distance\x18\x05 \x01(\x02H\x04R\x10gridFadeDistance\x88\x01\x01\x12\"\n" +
	"\n" +
	"point_size\x18\x06 \x01(\x02H\x05R\tpointSize\x88\x01\x01\x12$\n" +
	"\vpoint_color\x18\a \x01(\fH\x06R\n" +
	"pointColor\x88\x01\x01\x12\"\n" +
	"\n" +
	"line_width\x18\b \x01(\x02H\aR\tlineWidth\x88\x01\x01\x12+\n" +
	"\x0fline_point_size\x18\t \x01(\x02H\bR\rlinePointSize\x88\x01\x01\x12I\n" +
	"\x11render_arm_models\x18\n" +
	" \x01(\x0e2\x18.draw.v1.RenderArmModelsH\tR\x0frenderArmModels\x88\x01\x01\x12:\n" +
	"\rrender_shapes\x18\v \x03(\x0e2\x15.draw.v1.RenderShapesR\frenderShapesB\x0f\n" +
	"\r_scene_cameraB\a\n" +
	"\x05_gridB\x11\n" +
	"\x0f_grid_cell_sizeB\x14\n" +
	"\x12_grid_section_sizeB\x15\n" +
	"\x13_grid_fade_distanceB\r\n" +
	"\v_point_sizeB\x0e\n" +
	"\f_point_colorB\r\n" +
	"\v_line_widthB\x12\n" +
	"\x10_line_point_sizeB\x14\n" +
	"\x12_render_arm_models*\x9d\x01\n" +
	"\x0fRenderArmModels\x12!\n" +
	"\x1dRENDER_ARM_MODELS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRENDER_ARM_MODELS_COLLIDERS\x10\x01\x12)\n" +
	"%RENDER_ARM_MODELS_COLLIDERS_AND_MODEL\x10\x02\x12\x1b\n" +
	"\x17RENDER_ARM_MODELS_MODEL\x10\x03*\xac\x01\n" +
	"\fRenderShapes\x12\x1d\n" +
	"\x19RENDER_SHAPES_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RENDER_SHAPES_ARROWS\x10\x01\x12\x17\n" +
	"\x13RENDER_SHAPES_LINES\x10\x02\x12\x18\n" +
	"\x14RENDER_SHAPES_POINTS\x10\x03\x12\x17\n" +
	"\x13RENDER_SHAPES_MODEL\x10\x04\x12\x17\n" +
	"\x13RENDER_SHAPES_NURBS\x10\x05B2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_scene_proto_rawDescOnce sync.Once
	file_draw_v1_scene_proto_rawDescData []byte
)

func file_draw_v1_scene_proto_rawDescGZIP() []byte {
	file_draw_v1_scene_proto_rawDescOnce.Do(func() {
		file_draw_v1_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_scene_proto_rawDesc), len(file_draw_v1_scene_proto_rawDesc)))
	})
	return file_draw_v1_scene_proto_rawDescData
}

var file_draw_v1_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_draw_v1_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_draw_v1_scene_proto_goTypes = []any{
	(RenderArmModels)(0),       // 0: draw.v1.RenderArmModels
	(RenderShapes)(0),          // 1: draw.v1.RenderShapes
	(*OrthographicCamera)(nil), // 2: draw.v1.OrthographicCamera
	(*PerspectiveCamera)(nil),  // 3: draw.v1.PerspectiveCamera
	(*SceneCamera)(nil),        // 4: draw.v1.SceneCamera
	(*SceneMetadata)(nil),      // 5: draw.v1.SceneMetadata
	(*v1.Vector3)(nil),         // 6: viam.common.v1.Vector3
}
var file_draw_v1_scene_proto_depIdxs = []int32{
	6, // 0: draw.v1.SceneCamera.position:type_name -> viam.common.v1.Vector3
	6, // 1: draw.v1.SceneCamera.look_at:type_name -> viam.common.v1.Vector3
	3, // 2: draw.v1.SceneCamera.perspective_camera:type_name -> draw.v1.PerspectiveCamera
	2, // 3: draw.v1.SceneCamera.orthographic_camera:type_name -> draw.v1.OrthographicCamera
	4, // 4: draw.v1.SceneMetadata.scene_camera:type_name -> draw.v1.SceneCamera
	0, // 5: draw.v1.SceneMetadata.render_arm_models:type_name -> draw.v1.RenderArmModels
	1, // 6: draw.v1.SceneMetadata.render_shapes:type_name -> draw.v1.RenderShapes
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_draw_v1_scene_proto_init() }
func file_draw_v1_scene_proto_init() {
	if File_draw_v1_scene_proto != nil {
		return
	}
	file_draw_v1_scene_proto_msgTypes[0].OneofWrappers = []any{}
	file_draw_v1_scene_proto_msgTypes[2].OneofWrappers = []any{
		(*SceneCamera_PerspectiveCamera)(nil),
		(*SceneCamera_OrthographicCamera)(nil),
	}
	file_draw_v1_scene_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_scene_proto_rawDesc), len(file_draw_v1_scene_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_scene_proto_goTypes,
		DependencyIndexes: file_draw_v1_scene_proto_depIdxs,
		EnumInfos:         file_draw_v1_scene_proto_enumTypes,
		MessageInfos:      file_draw_v1_scene_proto_msgTypes,
	}.Build()
	File_draw_v1_scene_proto = out.File
	file_draw_v1_scene_proto_goTypes = nil
	file_draw_v1_scene_proto_depIdxs = nil
}
