// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/service.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityChangeType int32

const (
	EntityChangeType_ENTITY_CHANGE_TYPE_UNSPECIFIED EntityChangeType = 0
	EntityChangeType_ENTITY_CHANGE_TYPE_ADDED       EntityChangeType = 1
	EntityChangeType_ENTITY_CHANGE_TYPE_REMOVED     EntityChangeType = 2
	EntityChangeType_ENTITY_CHANGE_TYPE_UPDATED     EntityChangeType = 3
)

// Enum value maps for EntityChangeType.
var (
	EntityChangeType_name = map[int32]string{
		0: "ENTITY_CHANGE_TYPE_UNSPECIFIED",
		1: "ENTITY_CHANGE_TYPE_ADDED",
		2: "ENTITY_CHANGE_TYPE_REMOVED",
		3: "ENTITY_CHANGE_TYPE_UPDATED",
	}
	EntityChangeType_value = map[string]int32{
		"ENTITY_CHANGE_TYPE_UNSPECIFIED": 0,
		"ENTITY_CHANGE_TYPE_ADDED":       1,
		"ENTITY_CHANGE_TYPE_REMOVED":     2,
		"ENTITY_CHANGE_TYPE_UPDATED":     3,
	}
)

func (x EntityChangeType) Enum() *EntityChangeType {
	p := new(EntityChangeType)
	*p = x
	return p
}

func (x EntityChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_service_proto_enumTypes[0].Descriptor()
}

func (EntityChangeType) Type() protoreflect.EnumType {
	return &file_draw_v1_service_proto_enumTypes[0]
}

func (x EntityChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityChangeType.Descriptor instead.
func (EntityChangeType) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

type AddEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*AddEntityRequest_Transform
	//	*AddEntityRequest_Drawing
	Entity        isAddEntityRequest_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityRequest) Reset() {
	*x = AddEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityRequest) ProtoMessage() {}

func (x *AddEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityRequest.ProtoReflect.Descriptor instead.
func (*AddEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddEntityRequest) GetEntity() isAddEntityRequest_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *AddEntityRequest) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*AddEntityRequest_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *AddEntityRequest) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*AddEntityRequest_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

type isAddEntityRequest_Entity interface {
	isAddEntityRequest_Entity()
}

type AddEntityRequest_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,1,opt,name=transform,proto3,oneof"`
}

type AddEntityRequest_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,2,opt,name=drawing,proto3,oneof"`
}

func (*AddEntityRequest_Transform) isAddEntityRequest_Entity() {}

func (*AddEntityRequest_Drawing) isAddEntityRequest_Entity() {}

type AddEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityResponse) Reset() {
	*x = AddEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityResponse) ProtoMessage() {}

func (x *AddEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityResponse.ProtoReflect.Descriptor instead.
func (*AddEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddEntityResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type UpdateEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Types that are valid to be assigned to Entity:
	//
	//	*UpdateEntityRequest_Transform
	//	*UpdateEntityRequest_Drawing
	Entity isUpdateEntityRequest_Entity `protobuf_oneof:"entity"`
	// The fields to update on the entity. If empty, all fields are replaced.
	UpdatedFields *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityRequest) Reset() {
	*x = UpdateEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityRequest) ProtoMessage() {}

func (x *UpdateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEntityRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateEntityRequest) GetEntity() isUpdateEntityRequest_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *UpdateEntityRequest) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*UpdateEntityRequest_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *UpdateEntityRequest) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*UpdateEntityRequest_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

func (x *UpdateEntityRequest) GetUpdatedFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

type isUpdateEntityRequest_Entity interface {
	isUpdateEntityRequest_Entity()
}

type UpdateEntityRequest_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,2,opt,name=transform,proto3,oneof"`
}

type UpdateEntityRequest_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,3,opt,name=drawing,proto3,oneof"`
}

func (*UpdateEntityRequest_Transform) isUpdateEntityRequest_Entity() {}

func (*UpdateEntityRequest_Drawing) isUpdateEntityRequest_Entity() {}

type UpdateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityResponse) Reset() {
	*x = UpdateEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityResponse) ProtoMessage() {}

func (x *UpdateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{3}
}

type RemoveEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityRequest) Reset() {
	*x = RemoveEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityRequest) ProtoMessage() {}

func (x *RemoveEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityRequest.ProtoReflect.Descriptor instead.
func (*RemoveEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveEntityRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type RemoveEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityResponse) Reset() {
	*x = RemoveEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityResponse) ProtoMessage() {}

func (x *RemoveEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityResponse.ProtoReflect.Descriptor instead.
func (*RemoveEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{5}
}

type RemoveAllTransformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllTransformsRequest) Reset() {
	*x = RemoveAllTransformsRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllTransformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllTransformsRequest) ProtoMessage() {}

func (x *RemoveAllTransformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllTransformsRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllTransformsRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{6}
}

type RemoveAllTransformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllTransformsResponse) Reset() {
	*x = RemoveAllTransformsResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllTransformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllTransformsResponse) ProtoMessage() {}

func (x *RemoveAllTransformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllTransformsResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllTransformsResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveAllTransformsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamEntityChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntityChangesRequest) Reset() {
	*x = StreamEntityChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntityChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntityChangesRequest) ProtoMessage() {}

func (x *StreamEntityChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntityChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamEntityChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{8}
}

type StreamEntityChangesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChangeType EntityChangeType       `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=draw.v1.EntityChangeType" json:"change_type,omitempty"`
	// Types that are valid to be assigned to Entity:
	//
	//	*StreamEntityChangesResponse_Transform
	//	*StreamEntityChangesResponse_Drawing
	Entity        isStreamEntityChangesResponse_Entity `protobuf_oneof:"entity"`
	UpdatedFields *fieldmaskpb.FieldMask               `protobuf:"bytes,4,opt,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntityChangesResponse) Reset() {
	*x = StreamEntityChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntityChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntityChangesResponse) ProtoMessage() {}

func (x *StreamEntityChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntityChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamEntityChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEntityChangesResponse) GetChangeType() EntityChangeType {
	if x != nil {
		return x.ChangeType
	}
	return EntityChangeType_ENTITY_CHANGE_TYPE_UNSPECIFIED
}

func (x *StreamEntityChangesResponse) GetEntity() isStreamEntityChangesResponse_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *StreamEntityChangesResponse) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*StreamEntityChangesResponse_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *StreamEntityChangesResponse) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*StreamEntityChangesResponse_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

func (x *StreamEntityChangesResponse) GetUpdatedFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

type isStreamEntityChangesResponse_Entity interface {
	isStreamEntityChangesResponse_Entity()
}

type StreamEntityChangesResponse_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,2,opt,name=transform,proto3,oneof"`
}

type StreamEntityChangesResponse_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,3,opt,name=drawing,proto3,oneof"`
}

func (*StreamEntityChangesResponse_Transform) isStreamEntityChangesResponse_Entity() {}

func (*StreamEntityChangesResponse_Drawing) isStreamEntityChangesResponse_Entity() {}

type RemoveAllDrawingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllDrawingsRequest) Reset() {
	*x = RemoveAllDrawingsRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllDrawingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllDrawingsRequest) ProtoMessage() {}

func (x *RemoveAllDrawingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllDrawingsRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllDrawingsRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{10}
}

type RemoveAllDrawingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllDrawingsResponse) Reset() {
	*x = RemoveAllDrawingsResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllDrawingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllDrawingsResponse) ProtoMessage() {}

func (x *RemoveAllDrawingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllDrawingsResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllDrawingsResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveAllDrawingsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneMetadata *SceneMetadata         `protobuf:"bytes,1,opt,name=scene_metadata,json=sceneMetadata,proto3" json:"scene_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneRequest) Reset() {
	*x = SetSceneRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneRequest) ProtoMessage() {}

func (x *SetSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneRequest.ProtoReflect.Descriptor instead.
func (*SetSceneRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *SetSceneRequest) GetSceneMetadata() *SceneMetadata {
	if x != nil {
		return x.SceneMetadata
	}
	return nil
}

type SetSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneResponse) Reset() {
	*x = SetSceneResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneResponse) ProtoMessage() {}

func (x *SetSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneResponse.ProtoReflect.Descriptor instead.
func (*SetSceneResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{13}
}

type StreamSceneChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneChangesRequest) Reset() {
	*x = StreamSceneChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneChangesRequest) ProtoMessage() {}

func (x *StreamSceneChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamSceneChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{14}
}

type StreamSceneChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneMetadata *SceneMetadata         `protobuf:"bytes,1,opt,name=scene_metadata,json=sceneMetadata,proto3" json:"scene_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneChangesResponse) Reset() {
	*x = StreamSceneChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneChangesResponse) ProtoMessage() {}

func (x *StreamSceneChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamSceneChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *StreamSceneChangesResponse) GetSceneMetadata() *SceneMetadata {
	if x != nil {
		return x.SceneMetadata
	}
	return nil
}

type RemoveAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllRequest) Reset() {
	*x = RemoveAllRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllRequest) ProtoMessage() {}

func (x *RemoveAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{16}
}

type RemoveAllResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransformCount int32                  `protobuf:"varint,1,opt,name=transform_count,json=transformCount,proto3" json:"transform_count,omitempty"`
	DrawingCount   int32                  `protobuf:"varint,2,opt,name=drawing_count,json=drawingCount,proto3" json:"drawing_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveAllResponse) Reset() {
	*x = RemoveAllResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllResponse) ProtoMessage() {}

func (x *RemoveAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveAllResponse) GetTransformCount() int32 {
	if x != nil {
		return x.TransformCount
	}
	return 0
}

func (x *RemoveAllResponse) GetDrawingCount() int32 {
	if x != nil {
		return x.DrawingCount
	}
	return 0
}

type GetEntityChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Start         uint32                 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityChunkRequest) Reset() {
	*x = GetEntityChunkRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityChunkRequest) ProtoMessage() {}

func (x *GetEntityChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityChunkRequest.ProtoReflect.Descriptor instead.
func (*GetEntityChunkRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetEntityChunkRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *GetEntityChunkRequest) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

type GetEntityChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw position data for this chunk.
	Positions []byte `protobuf:"bytes,1,opt,name=positions,proto3" json:"positions,omitempty"`
	// Raw color data for this chunk (RGB bytes).
	Colors []byte `protobuf:"bytes,2,opt,name=colors,proto3" json:"colors,omitempty"`
	// Raw opacity data for this chunk.
	Opacities []byte `protobuf:"bytes,3,opt,name=opacities,proto3" json:"opacities,omitempty"`
	// The element offset this chunk starts at.
	Start uint32 `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	// True when this is the last available chunk AND all data has been received from the producer.
	Done          bool `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityChunkResponse) Reset() {
	*x = GetEntityChunkResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityChunkResponse) ProtoMessage() {}

func (x *GetEntityChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityChunkResponse.ProtoReflect.Descriptor instead.
func (*GetEntityChunkResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetEntityChunkResponse) GetPositions() []byte {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *GetEntityChunkResponse) GetColors() []byte {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *GetEntityChunkResponse) GetOpacities() []byte {
	if x != nil {
		return x.Opacities
	}
	return nil
}

func (x *GetEntityChunkResponse) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetEntityChunkResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_draw_v1_service_proto protoreflect.FileDescriptor

const file_draw_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15draw/v1/service.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\x1a\x15draw/v1/drawing.proto\x1a\x13draw/v1/scene.proto\x1a google/protobuf/field_mask.proto\"\x85\x01\n" +
	"\x10AddEntityRequest\x129\n" +
	"\ttransform\x18\x01 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x02 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawingB\b\n" +
	"\x06entity\"'\n" +
	"\x11AddEntityResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\xdf\x01\n" +
	"\x13UpdateEntityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x03 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawing\x12A\n" +
	"\x0eupdated_fields\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\rupdatedFieldsB\b\n" +
	"\x06entity\"\x16\n" +
	"\x14UpdateEntityResponse\")\n" +
	"\x13RemoveEntityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x16\n" +
	"\x14RemoveEntityResponse\"\x1c\n" +
	"\x1aRemoveAllTransformsRequest\"3\n" +
	"\x1bRemoveAllTransformsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x1c\n" +
	"\x1aStreamEntityChangesRequest\"\x8f\x02\n" +
	"\x1bStreamEntityChangesResponse\x12:\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x19.draw.v1.EntityChangeTypeR\n" +
	"changeType\x129\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x03 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawing\x12A\n" +
	"\x0eupdated_fields\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\rupdatedFieldsB\b\n" +
	"\x06entity\"\x1a\n" +
	"\x18RemoveAllDrawingsRequest\"1\n" +
	"\x19RemoveAllDrawingsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"P\n" +
	"\x0fSetSceneRequest\x12=\n" +
	"\x0escene_metadata\x18\x01 \x01(\v2\x16.draw.v1.SceneMetadataR\rsceneMetadata\"\x12\n" +
	"\x10SetSceneResponse\"\x1b\n" +
	"\x19StreamSceneChangesRequest\"[\n" +
	"\x1aStreamSceneChangesResponse\x12=\n" +
	"\x0escene_metadata\x18\x01 \x01(\v2\x16.draw.v1.SceneMetadataR\rsceneMetadata\"\x12\n" +
	"\x10RemoveAllRequest\"a\n" +
	"\x11RemoveAllResponse\x12'\n" +
	"\x0ftransform_count\x18\x01 \x01(\x05R\x0etransformCount\x12#\n" +
	"\rdrawing_count\x18\x02 \x01(\x05R\fdrawingCount\"A\n" +
	"\x15GetEntityChunkRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x14\n" +
	"\x05start\x18\x02 \x01(\rR\x05start\"\x96\x01\n" +
	"\x16GetEntityChunkResponse\x12\x1c\n" +
	"\tpositions\x18\x01 \x01(\fR\tpositions\x12\x16\n" +
	"\x06colors\x18\x02 \x01(\fR\x06colors\x12\x1c\n" +
	"\topacities\x18\x03 \x01(\fR\topacities\x12\x14\n" +
	"\x05start\x18\x04 \x01(\rR\x05start\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done*\x94\x01\n" +
	"\x10EntityChangeType\x12\"\n" +
	"\x1eENTITY_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ENTITY_CHANGE_TYPE_ADDED\x10\x01\x12\x1e\n" +
	"\x1aENTITY_CHANGE_TYPE_REMOVED\x10\x02\x12\x1e\n" +
	"\x1aENTITY_CHANGE_TYPE_UPDATED\x10\x032\xc6\x06\n" +
	"\vDrawService\x12B\n" +
	"\tAddEntity\x12\x19.draw.v1.AddEntityRequest\x1a\x1a.draw.v1.AddEntityResponse\x12K\n" +
	"\fUpdateEntity\x12\x1c.draw.v1.UpdateEntityRequest\x1a\x1d.draw.v1.UpdateEntityResponse\x12K\n" +
	"\fRemoveEntity\x12\x1c.draw.v1.RemoveEntityRequest\x1a\x1d.draw.v1.RemoveEntityResponse\x12b\n" +
	"\x13StreamEntityChanges\x12#.draw.v1.StreamEntityChangesRequest\x1a$.draw.v1.StreamEntityChangesResponse0\x01\x12?\n" +
	"\bSetScene\x12\x18.draw.v1.SetSceneRequest\x1a\x19.draw.v1.SetSceneResponse\x12_\n" +
	"\x12StreamSceneChanges\x12\".draw.v1.StreamSceneChangesRequest\x1a#.draw.v1.StreamSceneChangesResponse0\x01\x12`\n" +
	"\x13RemoveAllTransforms\x12#.draw.v1.RemoveAllTransformsRequest\x1a$.draw.v1.RemoveAllTransformsResponse\x12Z\n" +
	"\x11RemoveAllDrawings\x12!.draw.v1.RemoveAllDrawingsRequest\x1a\".draw.v1.RemoveAllDrawingsResponse\x12B\n" +
	"\tRemoveAll\x12\x19.draw.v1.RemoveAllRequest\x1a\x1a.draw.v1.RemoveAllResponse\x12Q\n" +
	"\x0eGetEntityChunk\x12\x1e.draw.v1.GetEntityChunkRequest\x1a\x1f.draw.v1.GetEntityChunkResponseB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_service_proto_rawDescOnce sync.Once
	file_draw_v1_service_proto_rawDescData []byte
)

func file_draw_v1_service_proto_rawDescGZIP() []byte {
	file_draw_v1_service_proto_rawDescOnce.Do(func() {
		file_draw_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)))
	})
	return file_draw_v1_service_proto_rawDescData
}

var file_draw_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_draw_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_draw_v1_service_proto_goTypes = []any{
	(EntityChangeType)(0),               // 0: draw.v1.EntityChangeType
	(*AddEntityRequest)(nil),            // 1: draw.v1.AddEntityRequest
	(*AddEntityResponse)(nil),           // 2: draw.v1.AddEntityResponse
	(*UpdateEntityRequest)(nil),         // 3: draw.v1.UpdateEntityRequest
	(*UpdateEntityResponse)(nil),        // 4: draw.v1.UpdateEntityResponse
	(*RemoveEntityRequest)(nil),         // 5: draw.v1.RemoveEntityRequest
	(*RemoveEntityResponse)(nil),        // 6: draw.v1.RemoveEntityResponse
	(*RemoveAllTransformsRequest)(nil),  // 7: draw.v1.RemoveAllTransformsRequest
	(*RemoveAllTransformsResponse)(nil), // 8: draw.v1.RemoveAllTransformsResponse
	(*StreamEntityChangesRequest)(nil),  // 9: draw.v1.StreamEntityChangesRequest
	(*StreamEntityChangesResponse)(nil), // 10: draw.v1.StreamEntityChangesResponse
	(*RemoveAllDrawingsRequest)(nil),    // 11: draw.v1.RemoveAllDrawingsRequest
	(*RemoveAllDrawingsResponse)(nil),   // 12: draw.v1.RemoveAllDrawingsResponse
	(*SetSceneRequest)(nil),             // 13: draw.v1.SetSceneRequest
	(*SetSceneResponse)(nil),            // 14: draw.v1.SetSceneResponse
	(*StreamSceneChangesRequest)(nil),   // 15: draw.v1.StreamSceneChangesRequest
	(*StreamSceneChangesResponse)(nil),  // 16: draw.v1.StreamSceneChangesResponse
	(*RemoveAllRequest)(nil),            // 17: draw.v1.RemoveAllRequest
	(*RemoveAllResponse)(nil),           // 18: draw.v1.RemoveAllResponse
	(*GetEntityChunkRequest)(nil),       // 19: draw.v1.GetEntityChunkRequest
	(*GetEntityChunkResponse)(nil),      // 20: draw.v1.GetEntityChunkResponse
	(*v1.Transform)(nil),                // 21: viam.common.v1.Transform
	(*Drawing)(nil),                     // 22: draw.v1.Drawing
	(*fieldmaskpb.FieldMask)(nil),       // 23: google.protobuf.FieldMask
	(*SceneMetadata)(nil),               // 24: draw.v1.SceneMetadata
}
var file_draw_v1_service_proto_depIdxs = []int32{
	21, // 0: draw.v1.AddEntityRequest.transform:type_name -> viam.common.v1.Transform
	22, // 1: draw.v1.AddEntityRequest.drawing:type_name -> draw.v1.Drawing
	21, // 2: draw.v1.UpdateEntityRequest.transform:type_name -> viam.common.v1.Transform
	22, // 3: draw.v1.UpdateEntityRequest.drawing:type_name -> draw.v1.Drawing
	23, // 4: draw.v1.UpdateEntityRequest.updated_fields:type_name -> google.protobuf.FieldMask
	0,  // 5: draw.v1.StreamEntityChangesResponse.change_type:type_name -> draw.v1.EntityChangeType
	21, // 6: draw.v1.StreamEntityChangesResponse.transform:type_name -> viam.common.v1.Transform
	22, // 7: draw.v1.StreamEntityChangesResponse.drawing:type_name -> draw.v1.Drawing
	23, // 8: draw.v1.StreamEntityChangesResponse.updated_fields:type_name -> google.protobuf.FieldMask
	24, // 9: draw.v1.SetSceneRequest.scene_metadata:type_name -> draw.v1.SceneMetadata
	24, // 10: draw.v1.StreamSceneChangesResponse.scene_metadata:type_name -> draw.v1.SceneMetadata
	1,  // 11: draw.v1.DrawService.AddEntity:input_type -> draw.v1.AddEntityRequest
	3,  // 12: draw.v1.DrawService.UpdateEntity:input_type -> draw.v1.UpdateEntityRequest
	5,  // 13: draw.v1.DrawService.RemoveEntity:input_type -> draw.v1.RemoveEntityRequest
	9,  // 14: draw.v1.DrawService.StreamEntityChanges:input_type -> draw.v1.StreamEntityChangesRequest
	13, // 15: draw.v1.DrawService.SetScene:input_type -> draw.v1.SetSceneRequest
	15, // 16: draw.v1.DrawService.StreamSceneChanges:input_type -> draw.v1.StreamSceneChangesRequest
	7,  // 17: draw.v1.DrawService.RemoveAllTransforms:input_type -> draw.v1.RemoveAllTransformsRequest
	11, // 18: draw.v1.DrawService.RemoveAllDrawings:input_type -> draw.v1.RemoveAllDrawingsRequest
	17, // 19: draw.v1.DrawService.RemoveAll:input_type -> draw.v1.RemoveAllRequest
	19, // 20: draw.v1.DrawService.GetEntityChunk:input_type -> draw.v1.GetEntityChunkRequest
	2,  // 21: draw.v1.DrawService.AddEntity:output_type -> draw.v1.AddEntityResponse
	4,  // 22: draw.v1.DrawService.UpdateEntity:output_type -> draw.v1.UpdateEntityResponse
	6,  // 23: draw.v1.DrawService.RemoveEntity:output_type -> draw.v1.RemoveEntityResponse
	10, // 24: draw.v1.DrawService.StreamEntityChanges:output_type -> draw.v1.StreamEntityChangesResponse
	14, // 25: draw.v1.DrawService.SetScene:output_type -> draw.v1.SetSceneResponse
	16, // 26: draw.v1.DrawService.StreamSceneChanges:output_type -> draw.v1.StreamSceneChangesResponse
	8,  // 27: draw.v1.DrawService.RemoveAllTransforms:output_type -> draw.v1.RemoveAllTransformsResponse
	12, // 28: draw.v1.DrawService.RemoveAllDrawings:output_type -> draw.v1.RemoveAllDrawingsResponse
	18, // 29: draw.v1.DrawService.RemoveAll:output_type -> draw.v1.RemoveAllResponse
	20, // 30: draw.v1.DrawService.GetEntityChunk:output_type -> draw.v1.GetEntityChunkResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_draw_v1_service_proto_init() }
func file_draw_v1_service_proto_init() {
	if File_draw_v1_service_proto != nil {
		return
	}
	file_draw_v1_drawing_proto_init()
	file_draw_v1_scene_proto_init()
	file_draw_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*AddEntityRequest_Transform)(nil),
		(*AddEntityRequest_Drawing)(nil),
	}
	file_draw_v1_service_proto_msgTypes[2].OneofWrappers = []any{
		(*UpdateEntityRequest_Transform)(nil),
		(*UpdateEntityRequest_Drawing)(nil),
	}
	file_draw_v1_service_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamEntityChangesResponse_Transform)(nil),
		(*StreamEntityChangesResponse_Drawing)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_draw_v1_service_proto_goTypes,
		DependencyIndexes: file_draw_v1_service_proto_depIdxs,
		EnumInfos:         file_draw_v1_service_proto_enumTypes,
		MessageInfos:      file_draw_v1_service_proto_msgTypes,
	}.Build()
	File_draw_v1_service_proto = out.File
	file_draw_v1_service_proto_goTypes = nil
	file_draw_v1_service_proto_depIdxs = nil
}
