// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/service.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_ADDED       ChangeType = 1
	ChangeType_CHANGE_TYPE_UPDATED     ChangeType = 2
	ChangeType_CHANGE_TYPE_REMOVED     ChangeType = 3
	ChangeType_CHANGE_TYPE_REMOVED_ALL ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_ADDED",
		2: "CHANGE_TYPE_UPDATED",
		3: "CHANGE_TYPE_REMOVED",
		4: "CHANGE_TYPE_REMOVED_ALL",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_ADDED":       1,
		"CHANGE_TYPE_UPDATED":     2,
		"CHANGE_TYPE_REMOVED":     3,
		"CHANGE_TYPE_REMOVED_ALL": 4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_service_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_draw_v1_service_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

type AddEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*AddEntityRequest_Transform
	//	*AddEntityRequest_Drawing
	Entity        isAddEntityRequest_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityRequest) Reset() {
	*x = AddEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityRequest) ProtoMessage() {}

func (x *AddEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityRequest.ProtoReflect.Descriptor instead.
func (*AddEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddEntityRequest) GetEntity() isAddEntityRequest_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *AddEntityRequest) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*AddEntityRequest_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *AddEntityRequest) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*AddEntityRequest_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

type isAddEntityRequest_Entity interface {
	isAddEntityRequest_Entity()
}

type AddEntityRequest_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,1,opt,name=transform,proto3,oneof"`
}

type AddEntityRequest_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,2,opt,name=drawing,proto3,oneof"`
}

func (*AddEntityRequest_Transform) isAddEntityRequest_Entity() {}

func (*AddEntityRequest_Drawing) isAddEntityRequest_Entity() {}

type AddEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEntityResponse) Reset() {
	*x = AddEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEntityResponse) ProtoMessage() {}

func (x *AddEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEntityResponse.ProtoReflect.Descriptor instead.
func (*AddEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{1}
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntityRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GetEntityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*GetEntityResponse_Transform
	//	*GetEntityResponse_Drawing
	Entity        isGetEntityResponse_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntityResponse) GetEntity() isGetEntityResponse_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *GetEntityResponse) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*GetEntityResponse_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *GetEntityResponse) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*GetEntityResponse_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

type isGetEntityResponse_Entity interface {
	isGetEntityResponse_Entity()
}

type GetEntityResponse_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,1,opt,name=transform,proto3,oneof"`
}

type GetEntityResponse_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,2,opt,name=drawing,proto3,oneof"`
}

func (*GetEntityResponse_Transform) isGetEntityResponse_Entity() {}

func (*GetEntityResponse_Drawing) isGetEntityResponse_Entity() {}

type ListEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesRequest) Reset() {
	*x = ListEntitiesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesRequest) ProtoMessage() {}

func (x *ListEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ListEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{4}
}

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transforms    []*v1.Transform        `protobuf:"bytes,1,rep,name=transforms,proto3" json:"transforms,omitempty"`
	Drawings      []*Drawing             `protobuf:"bytes,2,rep,name=drawings,proto3" json:"drawings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListEntitiesResponse) GetTransforms() []*v1.Transform {
	if x != nil {
		return x.Transforms
	}
	return nil
}

func (x *ListEntitiesResponse) GetDrawings() []*Drawing {
	if x != nil {
		return x.Drawings
	}
	return nil
}

type RemoveEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityRequest) Reset() {
	*x = RemoveEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityRequest) ProtoMessage() {}

func (x *RemoveEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityRequest.ProtoReflect.Descriptor instead.
func (*RemoveEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveEntityRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type RemoveEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEntityResponse) Reset() {
	*x = RemoveEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEntityResponse) ProtoMessage() {}

func (x *RemoveEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEntityResponse.ProtoReflect.Descriptor instead.
func (*RemoveEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{7}
}

type RemoveAllEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllEntitiesRequest) Reset() {
	*x = RemoveAllEntitiesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllEntitiesRequest) ProtoMessage() {}

func (x *RemoveAllEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllEntitiesRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{8}
}

type RemoveAllEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllEntitiesResponse) Reset() {
	*x = RemoveAllEntitiesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllEntitiesResponse) ProtoMessage() {}

func (x *RemoveAllEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllEntitiesResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{9}
}

type UpdateEntityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Types that are valid to be assigned to Entity:
	//
	//	*UpdateEntityRequest_Transform
	//	*UpdateEntityRequest_Drawing
	Entity        isUpdateEntityRequest_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityRequest) Reset() {
	*x = UpdateEntityRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityRequest) ProtoMessage() {}

func (x *UpdateEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntityRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEntityRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateEntityRequest) GetEntity() isUpdateEntityRequest_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *UpdateEntityRequest) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*UpdateEntityRequest_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *UpdateEntityRequest) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*UpdateEntityRequest_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

type isUpdateEntityRequest_Entity interface {
	isUpdateEntityRequest_Entity()
}

type UpdateEntityRequest_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,2,opt,name=transform,proto3,oneof"`
}

type UpdateEntityRequest_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,3,opt,name=drawing,proto3,oneof"`
}

func (*UpdateEntityRequest_Transform) isUpdateEntityRequest_Entity() {}

func (*UpdateEntityRequest_Drawing) isUpdateEntityRequest_Entity() {}

type UpdateEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntityResponse) Reset() {
	*x = UpdateEntityResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityResponse) ProtoMessage() {}

func (x *UpdateEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntityResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{11}
}

type EntityChange struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChangeType ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=draw.v1.ChangeType" json:"change_type,omitempty"`
	// Types that are valid to be assigned to Entity:
	//
	//	*EntityChange_Transform
	//	*EntityChange_Drawing
	Entity        isEntityChange_Entity  `protobuf_oneof:"entity"`
	UpdatedFields *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=updated_fields,json=updatedFields,proto3" json:"updated_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityChange) Reset() {
	*x = EntityChange{}
	mi := &file_draw_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityChange) ProtoMessage() {}

func (x *EntityChange) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityChange.ProtoReflect.Descriptor instead.
func (*EntityChange) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *EntityChange) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *EntityChange) GetEntity() isEntityChange_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityChange) GetTransform() *v1.Transform {
	if x != nil {
		if x, ok := x.Entity.(*EntityChange_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *EntityChange) GetDrawing() *Drawing {
	if x != nil {
		if x, ok := x.Entity.(*EntityChange_Drawing); ok {
			return x.Drawing
		}
	}
	return nil
}

func (x *EntityChange) GetUpdatedFields() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdatedFields
	}
	return nil
}

type isEntityChange_Entity interface {
	isEntityChange_Entity()
}

type EntityChange_Transform struct {
	Transform *v1.Transform `protobuf:"bytes,2,opt,name=transform,proto3,oneof"`
}

type EntityChange_Drawing struct {
	Drawing *Drawing `protobuf:"bytes,3,opt,name=drawing,proto3,oneof"`
}

func (*EntityChange_Transform) isEntityChange_Entity() {}

func (*EntityChange_Drawing) isEntityChange_Entity() {}

type StreamEntityChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntityChangesRequest) Reset() {
	*x = StreamEntityChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntityChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntityChangesRequest) ProtoMessage() {}

func (x *StreamEntityChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntityChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamEntityChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{13}
}

type StreamEntityChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityChange  *EntityChange          `protobuf:"bytes,1,opt,name=entity_change,json=entityChange,proto3" json:"entity_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEntityChangesResponse) Reset() {
	*x = StreamEntityChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEntityChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEntityChangesResponse) ProtoMessage() {}

func (x *StreamEntityChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEntityChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamEntityChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *StreamEntityChangesResponse) GetEntityChange() *EntityChange {
	if x != nil {
		return x.EntityChange
	}
	return nil
}

type SetSceneCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneCamera   *SceneCamera           `protobuf:"bytes,1,opt,name=scene_camera,json=sceneCamera,proto3" json:"scene_camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneCameraRequest) Reset() {
	*x = SetSceneCameraRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneCameraRequest) ProtoMessage() {}

func (x *SetSceneCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneCameraRequest.ProtoReflect.Descriptor instead.
func (*SetSceneCameraRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *SetSceneCameraRequest) GetSceneCamera() *SceneCamera {
	if x != nil {
		return x.SceneCamera
	}
	return nil
}

type SetSceneCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneCameraResponse) Reset() {
	*x = SetSceneCameraResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneCameraResponse) ProtoMessage() {}

func (x *SetSceneCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneCameraResponse.ProtoReflect.Descriptor instead.
func (*SetSceneCameraResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{16}
}

type StreamSceneCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneCameraRequest) Reset() {
	*x = StreamSceneCameraRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneCameraRequest) ProtoMessage() {}

func (x *StreamSceneCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneCameraRequest.ProtoReflect.Descriptor instead.
func (*StreamSceneCameraRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{17}
}

type StreamSceneCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneCamera   *SceneCamera           `protobuf:"bytes,1,opt,name=scene_camera,json=sceneCamera,proto3" json:"scene_camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneCameraResponse) Reset() {
	*x = StreamSceneCameraResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneCameraResponse) ProtoMessage() {}

func (x *StreamSceneCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneCameraResponse.ProtoReflect.Descriptor instead.
func (*StreamSceneCameraResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *StreamSceneCameraResponse) GetSceneCamera() *SceneCamera {
	if x != nil {
		return x.SceneCamera
	}
	return nil
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *RecordRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{20}
}

type StopRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordRequest) Reset() {
	*x = StopRecordRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordRequest) ProtoMessage() {}

func (x *StopRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordRequest.ProtoReflect.Descriptor instead.
func (*StopRecordRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{21}
}

type StopRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordResponse) Reset() {
	*x = StopRecordResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordResponse) ProtoMessage() {}

func (x *StopRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordResponse.ProtoReflect.Descriptor instead.
func (*StopRecordResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{22}
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	PlaybackSpeed float64                `protobuf:"fixed64,2,opt,name=playback_speed,json=playbackSpeed,proto3" json:"playback_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{23}
}

func (x *ReplayRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReplayRequest) GetPlaybackSpeed() float64 {
	if x != nil {
		return x.PlaybackSpeed
	}
	return 0
}

type ReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{24}
}

var File_draw_v1_service_proto protoreflect.FileDescriptor

const file_draw_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15draw/v1/service.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\x1a\x15draw/v1/drawing.proto\x1a\x13draw/v1/scene.proto\x1a google/protobuf/field_mask.proto\"\x85\x01\n" +
	"\x10AddEntityRequest\x129\n" +
	"\ttransform\x18\x01 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x02 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawingB\b\n" +
	"\x06entity\"\x13\n" +
	"\x11AddEntityResponse\"&\n" +
	"\x10GetEntityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x86\x01\n" +
	"\x11GetEntityResponse\x129\n" +
	"\ttransform\x18\x01 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x02 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawingB\b\n" +
	"\x06entity\"\x15\n" +
	"\x13ListEntitiesRequest\"\x7f\n" +
	"\x14ListEntitiesResponse\x129\n" +
	"\n" +
	"transforms\x18\x01 \x03(\v2\x19.viam.common.v1.TransformR\n" +
	"transforms\x12,\n" +
	"\bdrawings\x18\x02 \x03(\v2\x10.draw.v1.DrawingR\bdrawings\")\n" +
	"\x13RemoveEntityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x16\n" +
	"\x14RemoveEntityResponse\"\x1a\n" +
	"\x18RemoveAllEntitiesRequest\"\x1b\n" +
	"\x19RemoveAllEntitiesResponse\"\x9c\x01\n" +
	"\x13UpdateEntityRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x129\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x03 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawingB\b\n" +
	"\x06entity\"\x16\n" +
	"\x14UpdateEntityResponse\"\xfa\x01\n" +
	"\fEntityChange\x124\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x13.draw.v1.ChangeTypeR\n" +
	"changeType\x129\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformH\x00R\ttransform\x12,\n" +
	"\adrawing\x18\x03 \x01(\v2\x10.draw.v1.DrawingH\x00R\adrawing\x12A\n" +
	"\x0eupdated_fields\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\rupdatedFieldsB\b\n" +
	"\x06entity\"\x1c\n" +
	"\x1aStreamEntityChangesRequest\"Y\n" +
	"\x1bStreamEntityChangesResponse\x12:\n" +
	"\rentity_change\x18\x01 \x01(\v2\x15.draw.v1.EntityChangeR\fentityChange\"P\n" +
	"\x15SetSceneCameraRequest\x127\n" +
	"\fscene_camera\x18\x01 \x01(\v2\x14.draw.v1.SceneCameraR\vsceneCamera\"\x18\n" +
	"\x16SetSceneCameraResponse\"\x1a\n" +
	"\x18StreamSceneCameraRequest\"T\n" +
	"\x19StreamSceneCameraResponse\x127\n" +
	"\fscene_camera\x18\x01 \x01(\v2\x14.draw.v1.SceneCameraR\vsceneCamera\"+\n" +
	"\rRecordRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\x10\n" +
	"\x0eRecordResponse\"\x13\n" +
	"\x11StopRecordRequest\"\x14\n" +
	"\x12StopRecordResponse\"R\n" +
	"\rReplayRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12%\n" +
	"\x0eplayback_speed\x18\x02 \x01(\x01R\rplaybackSpeed\"\x10\n" +
	"\x0eReplayResponse*\x8f\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANGE_TYPE_ADDED\x10\x01\x12\x17\n" +
	"\x13CHANGE_TYPE_UPDATED\x10\x02\x12\x17\n" +
	"\x13CHANGE_TYPE_REMOVED\x10\x03\x12\x1b\n" +
	"\x17CHANGE_TYPE_REMOVED_ALL\x10\x042\xaa\a\n" +
	"\vDrawService\x12B\n" +
	"\tAddEntity\x12\x19.draw.v1.AddEntityRequest\x1a\x1a.draw.v1.AddEntityResponse\x12B\n" +
	"\tGetEntity\x12\x19.draw.v1.GetEntityRequest\x1a\x1a.draw.v1.GetEntityResponse\x12K\n" +
	"\fListEntities\x12\x1c.draw.v1.ListEntitiesRequest\x1a\x1d.draw.v1.ListEntitiesResponse\x12K\n" +
	"\fRemoveEntity\x12\x1c.draw.v1.RemoveEntityRequest\x1a\x1d.draw.v1.RemoveEntityResponse\x12Z\n" +
	"\x11RemoveAllEntities\x12!.draw.v1.RemoveAllEntitiesRequest\x1a\".draw.v1.RemoveAllEntitiesResponse\x12K\n" +
	"\fUpdateEntity\x12\x1c.draw.v1.UpdateEntityRequest\x1a\x1d.draw.v1.UpdateEntityResponse\x12Q\n" +
	"\x0eSetSceneCamera\x12\x1e.draw.v1.SetSceneCameraRequest\x1a\x1f.draw.v1.SetSceneCameraResponse\x12b\n" +
	"\x13StreamEntityChanges\x12#.draw.v1.StreamEntityChangesRequest\x1a$.draw.v1.StreamEntityChangesResponse0\x01\x12\\\n" +
	"\x11StreamSceneCamera\x12!.draw.v1.StreamSceneCameraRequest\x1a\".draw.v1.StreamSceneCameraResponse0\x01\x129\n" +
	"\x06Record\x12\x16.draw.v1.RecordRequest\x1a\x17.draw.v1.RecordResponse\x12E\n" +
	"\n" +
	"StopRecord\x12\x1a.draw.v1.StopRecordRequest\x1a\x1b.draw.v1.StopRecordResponse\x129\n" +
	"\x06Replay\x12\x16.draw.v1.ReplayRequest\x1a\x17.draw.v1.ReplayResponseB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_service_proto_rawDescOnce sync.Once
	file_draw_v1_service_proto_rawDescData []byte
)

func file_draw_v1_service_proto_rawDescGZIP() []byte {
	file_draw_v1_service_proto_rawDescOnce.Do(func() {
		file_draw_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)))
	})
	return file_draw_v1_service_proto_rawDescData
}

var file_draw_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_draw_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_draw_v1_service_proto_goTypes = []any{
	(ChangeType)(0),                     // 0: draw.v1.ChangeType
	(*AddEntityRequest)(nil),            // 1: draw.v1.AddEntityRequest
	(*AddEntityResponse)(nil),           // 2: draw.v1.AddEntityResponse
	(*GetEntityRequest)(nil),            // 3: draw.v1.GetEntityRequest
	(*GetEntityResponse)(nil),           // 4: draw.v1.GetEntityResponse
	(*ListEntitiesRequest)(nil),         // 5: draw.v1.ListEntitiesRequest
	(*ListEntitiesResponse)(nil),        // 6: draw.v1.ListEntitiesResponse
	(*RemoveEntityRequest)(nil),         // 7: draw.v1.RemoveEntityRequest
	(*RemoveEntityResponse)(nil),        // 8: draw.v1.RemoveEntityResponse
	(*RemoveAllEntitiesRequest)(nil),    // 9: draw.v1.RemoveAllEntitiesRequest
	(*RemoveAllEntitiesResponse)(nil),   // 10: draw.v1.RemoveAllEntitiesResponse
	(*UpdateEntityRequest)(nil),         // 11: draw.v1.UpdateEntityRequest
	(*UpdateEntityResponse)(nil),        // 12: draw.v1.UpdateEntityResponse
	(*EntityChange)(nil),                // 13: draw.v1.EntityChange
	(*StreamEntityChangesRequest)(nil),  // 14: draw.v1.StreamEntityChangesRequest
	(*StreamEntityChangesResponse)(nil), // 15: draw.v1.StreamEntityChangesResponse
	(*SetSceneCameraRequest)(nil),       // 16: draw.v1.SetSceneCameraRequest
	(*SetSceneCameraResponse)(nil),      // 17: draw.v1.SetSceneCameraResponse
	(*StreamSceneCameraRequest)(nil),    // 18: draw.v1.StreamSceneCameraRequest
	(*StreamSceneCameraResponse)(nil),   // 19: draw.v1.StreamSceneCameraResponse
	(*RecordRequest)(nil),               // 20: draw.v1.RecordRequest
	(*RecordResponse)(nil),              // 21: draw.v1.RecordResponse
	(*StopRecordRequest)(nil),           // 22: draw.v1.StopRecordRequest
	(*StopRecordResponse)(nil),          // 23: draw.v1.StopRecordResponse
	(*ReplayRequest)(nil),               // 24: draw.v1.ReplayRequest
	(*ReplayResponse)(nil),              // 25: draw.v1.ReplayResponse
	(*v1.Transform)(nil),                // 26: viam.common.v1.Transform
	(*Drawing)(nil),                     // 27: draw.v1.Drawing
	(*fieldmaskpb.FieldMask)(nil),       // 28: google.protobuf.FieldMask
	(*SceneCamera)(nil),                 // 29: draw.v1.SceneCamera
}
var file_draw_v1_service_proto_depIdxs = []int32{
	26, // 0: draw.v1.AddEntityRequest.transform:type_name -> viam.common.v1.Transform
	27, // 1: draw.v1.AddEntityRequest.drawing:type_name -> draw.v1.Drawing
	26, // 2: draw.v1.GetEntityResponse.transform:type_name -> viam.common.v1.Transform
	27, // 3: draw.v1.GetEntityResponse.drawing:type_name -> draw.v1.Drawing
	26, // 4: draw.v1.ListEntitiesResponse.transforms:type_name -> viam.common.v1.Transform
	27, // 5: draw.v1.ListEntitiesResponse.drawings:type_name -> draw.v1.Drawing
	26, // 6: draw.v1.UpdateEntityRequest.transform:type_name -> viam.common.v1.Transform
	27, // 7: draw.v1.UpdateEntityRequest.drawing:type_name -> draw.v1.Drawing
	0,  // 8: draw.v1.EntityChange.change_type:type_name -> draw.v1.ChangeType
	26, // 9: draw.v1.EntityChange.transform:type_name -> viam.common.v1.Transform
	27, // 10: draw.v1.EntityChange.drawing:type_name -> draw.v1.Drawing
	28, // 11: draw.v1.EntityChange.updated_fields:type_name -> google.protobuf.FieldMask
	13, // 12: draw.v1.StreamEntityChangesResponse.entity_change:type_name -> draw.v1.EntityChange
	29, // 13: draw.v1.SetSceneCameraRequest.scene_camera:type_name -> draw.v1.SceneCamera
	29, // 14: draw.v1.StreamSceneCameraResponse.scene_camera:type_name -> draw.v1.SceneCamera
	1,  // 15: draw.v1.DrawService.AddEntity:input_type -> draw.v1.AddEntityRequest
	3,  // 16: draw.v1.DrawService.GetEntity:input_type -> draw.v1.GetEntityRequest
	5,  // 17: draw.v1.DrawService.ListEntities:input_type -> draw.v1.ListEntitiesRequest
	7,  // 18: draw.v1.DrawService.RemoveEntity:input_type -> draw.v1.RemoveEntityRequest
	9,  // 19: draw.v1.DrawService.RemoveAllEntities:input_type -> draw.v1.RemoveAllEntitiesRequest
	11, // 20: draw.v1.DrawService.UpdateEntity:input_type -> draw.v1.UpdateEntityRequest
	16, // 21: draw.v1.DrawService.SetSceneCamera:input_type -> draw.v1.SetSceneCameraRequest
	14, // 22: draw.v1.DrawService.StreamEntityChanges:input_type -> draw.v1.StreamEntityChangesRequest
	18, // 23: draw.v1.DrawService.StreamSceneCamera:input_type -> draw.v1.StreamSceneCameraRequest
	20, // 24: draw.v1.DrawService.Record:input_type -> draw.v1.RecordRequest
	22, // 25: draw.v1.DrawService.StopRecord:input_type -> draw.v1.StopRecordRequest
	24, // 26: draw.v1.DrawService.Replay:input_type -> draw.v1.ReplayRequest
	2,  // 27: draw.v1.DrawService.AddEntity:output_type -> draw.v1.AddEntityResponse
	4,  // 28: draw.v1.DrawService.GetEntity:output_type -> draw.v1.GetEntityResponse
	6,  // 29: draw.v1.DrawService.ListEntities:output_type -> draw.v1.ListEntitiesResponse
	8,  // 30: draw.v1.DrawService.RemoveEntity:output_type -> draw.v1.RemoveEntityResponse
	10, // 31: draw.v1.DrawService.RemoveAllEntities:output_type -> draw.v1.RemoveAllEntitiesResponse
	12, // 32: draw.v1.DrawService.UpdateEntity:output_type -> draw.v1.UpdateEntityResponse
	17, // 33: draw.v1.DrawService.SetSceneCamera:output_type -> draw.v1.SetSceneCameraResponse
	15, // 34: draw.v1.DrawService.StreamEntityChanges:output_type -> draw.v1.StreamEntityChangesResponse
	19, // 35: draw.v1.DrawService.StreamSceneCamera:output_type -> draw.v1.StreamSceneCameraResponse
	21, // 36: draw.v1.DrawService.Record:output_type -> draw.v1.RecordResponse
	23, // 37: draw.v1.DrawService.StopRecord:output_type -> draw.v1.StopRecordResponse
	25, // 38: draw.v1.DrawService.Replay:output_type -> draw.v1.ReplayResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_draw_v1_service_proto_init() }
func file_draw_v1_service_proto_init() {
	if File_draw_v1_service_proto != nil {
		return
	}
	file_draw_v1_drawing_proto_init()
	file_draw_v1_scene_proto_init()
	file_draw_v1_service_proto_msgTypes[0].OneofWrappers = []any{
		(*AddEntityRequest_Transform)(nil),
		(*AddEntityRequest_Drawing)(nil),
	}
	file_draw_v1_service_proto_msgTypes[3].OneofWrappers = []any{
		(*GetEntityResponse_Transform)(nil),
		(*GetEntityResponse_Drawing)(nil),
	}
	file_draw_v1_service_proto_msgTypes[10].OneofWrappers = []any{
		(*UpdateEntityRequest_Transform)(nil),
		(*UpdateEntityRequest_Drawing)(nil),
	}
	file_draw_v1_service_proto_msgTypes[12].OneofWrappers = []any{
		(*EntityChange_Transform)(nil),
		(*EntityChange_Drawing)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_draw_v1_service_proto_goTypes,
		DependencyIndexes: file_draw_v1_service_proto_depIdxs,
		EnumInfos:         file_draw_v1_service_proto_enumTypes,
		MessageInfos:      file_draw_v1_service_proto_msgTypes,
	}.Build()
	File_draw_v1_service_proto = out.File
	file_draw_v1_service_proto_goTypes = nil
	file_draw_v1_service_proto_depIdxs = nil
}
