// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: draw/v1/service.proto

package drawv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DrawService_AddEntity_FullMethodName           = "/draw.v1.DrawService/AddEntity"
	DrawService_GetEntity_FullMethodName           = "/draw.v1.DrawService/GetEntity"
	DrawService_ListEntities_FullMethodName        = "/draw.v1.DrawService/ListEntities"
	DrawService_RemoveEntity_FullMethodName        = "/draw.v1.DrawService/RemoveEntity"
	DrawService_RemoveAllEntities_FullMethodName   = "/draw.v1.DrawService/RemoveAllEntities"
	DrawService_UpdateEntity_FullMethodName        = "/draw.v1.DrawService/UpdateEntity"
	DrawService_SetSceneCamera_FullMethodName      = "/draw.v1.DrawService/SetSceneCamera"
	DrawService_StreamEntityChanges_FullMethodName = "/draw.v1.DrawService/StreamEntityChanges"
	DrawService_StreamSceneCamera_FullMethodName   = "/draw.v1.DrawService/StreamSceneCamera"
	DrawService_Record_FullMethodName              = "/draw.v1.DrawService/Record"
	DrawService_StopRecord_FullMethodName          = "/draw.v1.DrawService/StopRecord"
	DrawService_Replay_FullMethodName              = "/draw.v1.DrawService/Replay"
)

// DrawServiceClient is the client API for DrawService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DrawService is the service for drawing to a local visualizer instance
type DrawServiceClient interface {
	// AddEntity adds an entity to the scene
	AddEntity(ctx context.Context, in *AddEntityRequest, opts ...grpc.CallOption) (*AddEntityResponse, error)
	// GetEntity returns an entity by its name
	GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error)
	// ListEntities returns all entities in the scene
	ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error)
	// RemoveEntity removes an entity by its name
	RemoveEntity(ctx context.Context, in *RemoveEntityRequest, opts ...grpc.CallOption) (*RemoveEntityResponse, error)
	// RemoveAllEntities removes all entities from the scene
	RemoveAllEntities(ctx context.Context, in *RemoveAllEntitiesRequest, opts ...grpc.CallOption) (*RemoveAllEntitiesResponse, error)
	// UpdateEntity updates an entity by its name
	UpdateEntity(ctx context.Context, in *UpdateEntityRequest, opts ...grpc.CallOption) (*UpdateEntityResponse, error)
	// SetSceneCamera sets the scene camera
	SetSceneCamera(ctx context.Context, in *SetSceneCameraRequest, opts ...grpc.CallOption) (*SetSceneCameraResponse, error)
	// StreamEntityChanges streams changes to the entities in the scene
	StreamEntityChanges(ctx context.Context, in *StreamEntityChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEntityChangesResponse], error)
	// StreamSceneCamera streams changes to the scene camera
	StreamSceneCamera(ctx context.Context, in *StreamSceneCameraRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSceneCameraResponse], error)
	// Record records all operations between now and `StopRecord` to the input filename.
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	// StopRecord stops recording.
	StopRecord(ctx context.Context, in *StopRecordRequest, opts ...grpc.CallOption) (*StopRecordResponse, error)
	// Replay replays a prior recorded rendering.
	Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
}

type drawServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDrawServiceClient(cc grpc.ClientConnInterface) DrawServiceClient {
	return &drawServiceClient{cc}
}

func (c *drawServiceClient) AddEntity(ctx context.Context, in *AddEntityRequest, opts ...grpc.CallOption) (*AddEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEntityResponse)
	err := c.cc.Invoke(ctx, DrawService_AddEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) GetEntity(ctx context.Context, in *GetEntityRequest, opts ...grpc.CallOption) (*GetEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityResponse)
	err := c.cc.Invoke(ctx, DrawService_GetEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) ListEntities(ctx context.Context, in *ListEntitiesRequest, opts ...grpc.CallOption) (*ListEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitiesResponse)
	err := c.cc.Invoke(ctx, DrawService_ListEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) RemoveEntity(ctx context.Context, in *RemoveEntityRequest, opts ...grpc.CallOption) (*RemoveEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveEntityResponse)
	err := c.cc.Invoke(ctx, DrawService_RemoveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) RemoveAllEntities(ctx context.Context, in *RemoveAllEntitiesRequest, opts ...grpc.CallOption) (*RemoveAllEntitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAllEntitiesResponse)
	err := c.cc.Invoke(ctx, DrawService_RemoveAllEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) UpdateEntity(ctx context.Context, in *UpdateEntityRequest, opts ...grpc.CallOption) (*UpdateEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEntityResponse)
	err := c.cc.Invoke(ctx, DrawService_UpdateEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) SetSceneCamera(ctx context.Context, in *SetSceneCameraRequest, opts ...grpc.CallOption) (*SetSceneCameraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSceneCameraResponse)
	err := c.cc.Invoke(ctx, DrawService_SetSceneCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) StreamEntityChanges(ctx context.Context, in *StreamEntityChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEntityChangesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DrawService_ServiceDesc.Streams[0], DrawService_StreamEntityChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEntityChangesRequest, StreamEntityChangesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrawService_StreamEntityChangesClient = grpc.ServerStreamingClient[StreamEntityChangesResponse]

func (c *drawServiceClient) StreamSceneCamera(ctx context.Context, in *StreamSceneCameraRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamSceneCameraResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DrawService_ServiceDesc.Streams[1], DrawService_StreamSceneCamera_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSceneCameraRequest, StreamSceneCameraResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrawService_StreamSceneCameraClient = grpc.ServerStreamingClient[StreamSceneCameraResponse]

func (c *drawServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, DrawService_Record_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) StopRecord(ctx context.Context, in *StopRecordRequest, opts ...grpc.CallOption) (*StopRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRecordResponse)
	err := c.cc.Invoke(ctx, DrawService_StopRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drawServiceClient) Replay(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, DrawService_Replay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrawServiceServer is the server API for DrawService service.
// All implementations must embed UnimplementedDrawServiceServer
// for forward compatibility.
//
// DrawService is the service for drawing to a local visualizer instance
type DrawServiceServer interface {
	// AddEntity adds an entity to the scene
	AddEntity(context.Context, *AddEntityRequest) (*AddEntityResponse, error)
	// GetEntity returns an entity by its name
	GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error)
	// ListEntities returns all entities in the scene
	ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error)
	// RemoveEntity removes an entity by its name
	RemoveEntity(context.Context, *RemoveEntityRequest) (*RemoveEntityResponse, error)
	// RemoveAllEntities removes all entities from the scene
	RemoveAllEntities(context.Context, *RemoveAllEntitiesRequest) (*RemoveAllEntitiesResponse, error)
	// UpdateEntity updates an entity by its name
	UpdateEntity(context.Context, *UpdateEntityRequest) (*UpdateEntityResponse, error)
	// SetSceneCamera sets the scene camera
	SetSceneCamera(context.Context, *SetSceneCameraRequest) (*SetSceneCameraResponse, error)
	// StreamEntityChanges streams changes to the entities in the scene
	StreamEntityChanges(*StreamEntityChangesRequest, grpc.ServerStreamingServer[StreamEntityChangesResponse]) error
	// StreamSceneCamera streams changes to the scene camera
	StreamSceneCamera(*StreamSceneCameraRequest, grpc.ServerStreamingServer[StreamSceneCameraResponse]) error
	// Record records all operations between now and `StopRecord` to the input filename.
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
	// StopRecord stops recording.
	StopRecord(context.Context, *StopRecordRequest) (*StopRecordResponse, error)
	// Replay replays a prior recorded rendering.
	Replay(context.Context, *ReplayRequest) (*ReplayResponse, error)
	mustEmbedUnimplementedDrawServiceServer()
}

// UnimplementedDrawServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDrawServiceServer struct{}

func (UnimplementedDrawServiceServer) AddEntity(context.Context, *AddEntityRequest) (*AddEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEntity not implemented")
}
func (UnimplementedDrawServiceServer) GetEntity(context.Context, *GetEntityRequest) (*GetEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntity not implemented")
}
func (UnimplementedDrawServiceServer) ListEntities(context.Context, *ListEntitiesRequest) (*ListEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntities not implemented")
}
func (UnimplementedDrawServiceServer) RemoveEntity(context.Context, *RemoveEntityRequest) (*RemoveEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveEntity not implemented")
}
func (UnimplementedDrawServiceServer) RemoveAllEntities(context.Context, *RemoveAllEntitiesRequest) (*RemoveAllEntitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAllEntities not implemented")
}
func (UnimplementedDrawServiceServer) UpdateEntity(context.Context, *UpdateEntityRequest) (*UpdateEntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEntity not implemented")
}
func (UnimplementedDrawServiceServer) SetSceneCamera(context.Context, *SetSceneCameraRequest) (*SetSceneCameraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSceneCamera not implemented")
}
func (UnimplementedDrawServiceServer) StreamEntityChanges(*StreamEntityChangesRequest, grpc.ServerStreamingServer[StreamEntityChangesResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEntityChanges not implemented")
}
func (UnimplementedDrawServiceServer) StreamSceneCamera(*StreamSceneCameraRequest, grpc.ServerStreamingServer[StreamSceneCameraResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamSceneCamera not implemented")
}
func (UnimplementedDrawServiceServer) Record(context.Context, *RecordRequest) (*RecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Record not implemented")
}
func (UnimplementedDrawServiceServer) StopRecord(context.Context, *StopRecordRequest) (*StopRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecord not implemented")
}
func (UnimplementedDrawServiceServer) Replay(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replay not implemented")
}
func (UnimplementedDrawServiceServer) mustEmbedUnimplementedDrawServiceServer() {}
func (UnimplementedDrawServiceServer) testEmbeddedByValue()                     {}

// UnsafeDrawServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrawServiceServer will
// result in compilation errors.
type UnsafeDrawServiceServer interface {
	mustEmbedUnimplementedDrawServiceServer()
}

func RegisterDrawServiceServer(s grpc.ServiceRegistrar, srv DrawServiceServer) {
	// If the following call panics, it indicates UnimplementedDrawServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DrawService_ServiceDesc, srv)
}

func _DrawService_AddEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).AddEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_AddEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).AddEntity(ctx, req.(*AddEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_GetEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).GetEntity(ctx, req.(*GetEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_ListEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).ListEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_ListEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).ListEntities(ctx, req.(*ListEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_RemoveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).RemoveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_RemoveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).RemoveEntity(ctx, req.(*RemoveEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_RemoveAllEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAllEntitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).RemoveAllEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_RemoveAllEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).RemoveAllEntities(ctx, req.(*RemoveAllEntitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_UpdateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).UpdateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_UpdateEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).UpdateEntity(ctx, req.(*UpdateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_SetSceneCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSceneCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).SetSceneCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_SetSceneCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).SetSceneCamera(ctx, req.(*SetSceneCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_StreamEntityChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEntityChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DrawServiceServer).StreamEntityChanges(m, &grpc.GenericServerStream[StreamEntityChangesRequest, StreamEntityChangesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrawService_StreamEntityChangesServer = grpc.ServerStreamingServer[StreamEntityChangesResponse]

func _DrawService_StreamSceneCamera_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSceneCameraRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DrawServiceServer).StreamSceneCamera(m, &grpc.GenericServerStream[StreamSceneCameraRequest, StreamSceneCameraResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DrawService_StreamSceneCameraServer = grpc.ServerStreamingServer[StreamSceneCameraResponse]

func _DrawService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_Record_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_StopRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).StopRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_StopRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).StopRecord(ctx, req.(*StopRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrawService_Replay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawServiceServer).Replay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DrawService_Replay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawServiceServer).Replay(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DrawService_ServiceDesc is the grpc.ServiceDesc for DrawService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrawService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "draw.v1.DrawService",
	HandlerType: (*DrawServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEntity",
			Handler:    _DrawService_AddEntity_Handler,
		},
		{
			MethodName: "GetEntity",
			Handler:    _DrawService_GetEntity_Handler,
		},
		{
			MethodName: "ListEntities",
			Handler:    _DrawService_ListEntities_Handler,
		},
		{
			MethodName: "RemoveEntity",
			Handler:    _DrawService_RemoveEntity_Handler,
		},
		{
			MethodName: "RemoveAllEntities",
			Handler:    _DrawService_RemoveAllEntities_Handler,
		},
		{
			MethodName: "UpdateEntity",
			Handler:    _DrawService_UpdateEntity_Handler,
		},
		{
			MethodName: "SetSceneCamera",
			Handler:    _DrawService_SetSceneCamera_Handler,
		},
		{
			MethodName: "Record",
			Handler:    _DrawService_Record_Handler,
		},
		{
			MethodName: "StopRecord",
			Handler:    _DrawService_StopRecord_Handler,
		},
		{
			MethodName: "Replay",
			Handler:    _DrawService_Replay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEntityChanges",
			Handler:       _DrawService_StreamEntityChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSceneCamera",
			Handler:       _DrawService_StreamSceneCamera_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "draw/v1/service.proto",
}
