// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/service.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_ADDED       ChangeType = 1
	ChangeType_CHANGE_TYPE_REMOVED     ChangeType = 2
	ChangeType_CHANGE_TYPE_UPDATED     ChangeType = 3
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_ADDED",
		2: "CHANGE_TYPE_REMOVED",
		3: "CHANGE_TYPE_UPDATED",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_ADDED":       1,
		"CHANGE_TYPE_REMOVED":     2,
		"CHANGE_TYPE_UPDATED":     3,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_draw_v1_service_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_draw_v1_service_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

type AddTransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transform     *v1.Transform          `protobuf:"bytes,1,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransformRequest) Reset() {
	*x = AddTransformRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransformRequest) ProtoMessage() {}

func (x *AddTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransformRequest.ProtoReflect.Descriptor instead.
func (*AddTransformRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddTransformRequest) GetTransform() *v1.Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type AddTransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTransformResponse) Reset() {
	*x = AddTransformResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTransformResponse) ProtoMessage() {}

func (x *AddTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTransformResponse.ProtoReflect.Descriptor instead.
func (*AddTransformResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddTransformResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type UpdateTransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Transform     *v1.Transform          `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransformRequest) Reset() {
	*x = UpdateTransformRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransformRequest) ProtoMessage() {}

func (x *UpdateTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransformRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransformRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTransformRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateTransformRequest) GetTransform() *v1.Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type UpdateTransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransformResponse) Reset() {
	*x = UpdateTransformResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransformResponse) ProtoMessage() {}

func (x *UpdateTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransformResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransformResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{3}
}

type RemoveTransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTransformRequest) Reset() {
	*x = RemoveTransformRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTransformRequest) ProtoMessage() {}

func (x *RemoveTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTransformRequest.ProtoReflect.Descriptor instead.
func (*RemoveTransformRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveTransformRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type RemoveTransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTransformResponse) Reset() {
	*x = RemoveTransformResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTransformResponse) ProtoMessage() {}

func (x *RemoveTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTransformResponse.ProtoReflect.Descriptor instead.
func (*RemoveTransformResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{5}
}

type RemoveAllTransformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllTransformsRequest) Reset() {
	*x = RemoveAllTransformsRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllTransformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllTransformsRequest) ProtoMessage() {}

func (x *RemoveAllTransformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllTransformsRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllTransformsRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{6}
}

type RemoveAllTransformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllTransformsResponse) Reset() {
	*x = RemoveAllTransformsResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllTransformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllTransformsResponse) ProtoMessage() {}

func (x *RemoveAllTransformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllTransformsResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllTransformsResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveAllTransformsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamTransformChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTransformChangesRequest) Reset() {
	*x = StreamTransformChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTransformChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTransformChangesRequest) ProtoMessage() {}

func (x *StreamTransformChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTransformChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamTransformChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{8}
}

type StreamTransformChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=draw.v1.ChangeType" json:"change_type,omitempty"`
	Transform     *v1.Transform          `protobuf:"bytes,2,opt,name=transform,proto3" json:"transform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTransformChangesResponse) Reset() {
	*x = StreamTransformChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTransformChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTransformChangesResponse) ProtoMessage() {}

func (x *StreamTransformChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTransformChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamTransformChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *StreamTransformChangesResponse) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *StreamTransformChangesResponse) GetTransform() *v1.Transform {
	if x != nil {
		return x.Transform
	}
	return nil
}

type AddDrawingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drawing       *Drawing               `protobuf:"bytes,1,opt,name=drawing,proto3" json:"drawing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDrawingRequest) Reset() {
	*x = AddDrawingRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDrawingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDrawingRequest) ProtoMessage() {}

func (x *AddDrawingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDrawingRequest.ProtoReflect.Descriptor instead.
func (*AddDrawingRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *AddDrawingRequest) GetDrawing() *Drawing {
	if x != nil {
		return x.Drawing
	}
	return nil
}

type AddDrawingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDrawingResponse) Reset() {
	*x = AddDrawingResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDrawingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDrawingResponse) ProtoMessage() {}

func (x *AddDrawingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDrawingResponse.ProtoReflect.Descriptor instead.
func (*AddDrawingResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *AddDrawingResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type UpdateDrawingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Drawing       *Drawing               `protobuf:"bytes,2,opt,name=drawing,proto3" json:"drawing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDrawingRequest) Reset() {
	*x = UpdateDrawingRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDrawingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrawingRequest) ProtoMessage() {}

func (x *UpdateDrawingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrawingRequest.ProtoReflect.Descriptor instead.
func (*UpdateDrawingRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDrawingRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *UpdateDrawingRequest) GetDrawing() *Drawing {
	if x != nil {
		return x.Drawing
	}
	return nil
}

type UpdateDrawingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDrawingResponse) Reset() {
	*x = UpdateDrawingResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDrawingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDrawingResponse) ProtoMessage() {}

func (x *UpdateDrawingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDrawingResponse.ProtoReflect.Descriptor instead.
func (*UpdateDrawingResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{13}
}

type RemoveDrawingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDrawingRequest) Reset() {
	*x = RemoveDrawingRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDrawingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDrawingRequest) ProtoMessage() {}

func (x *RemoveDrawingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDrawingRequest.ProtoReflect.Descriptor instead.
func (*RemoveDrawingRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveDrawingRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type RemoveDrawingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDrawingResponse) Reset() {
	*x = RemoveDrawingResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDrawingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDrawingResponse) ProtoMessage() {}

func (x *RemoveDrawingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDrawingResponse.ProtoReflect.Descriptor instead.
func (*RemoveDrawingResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{15}
}

type RemoveAllDrawingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllDrawingsRequest) Reset() {
	*x = RemoveAllDrawingsRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllDrawingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllDrawingsRequest) ProtoMessage() {}

func (x *RemoveAllDrawingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllDrawingsRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllDrawingsRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{16}
}

type RemoveAllDrawingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllDrawingsResponse) Reset() {
	*x = RemoveAllDrawingsResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllDrawingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllDrawingsResponse) ProtoMessage() {}

func (x *RemoveAllDrawingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllDrawingsResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllDrawingsResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveAllDrawingsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamDrawingChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDrawingChangesRequest) Reset() {
	*x = StreamDrawingChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDrawingChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDrawingChangesRequest) ProtoMessage() {}

func (x *StreamDrawingChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDrawingChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamDrawingChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{18}
}

type StreamDrawingChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=draw.v1.ChangeType" json:"change_type,omitempty"`
	Drawing       *Drawing               `protobuf:"bytes,2,opt,name=drawing,proto3" json:"drawing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDrawingChangesResponse) Reset() {
	*x = StreamDrawingChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDrawingChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDrawingChangesResponse) ProtoMessage() {}

func (x *StreamDrawingChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDrawingChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamDrawingChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *StreamDrawingChangesResponse) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *StreamDrawingChangesResponse) GetDrawing() *Drawing {
	if x != nil {
		return x.Drawing
	}
	return nil
}

type StreamSceneChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneChangesRequest) Reset() {
	*x = StreamSceneChangesRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneChangesRequest) ProtoMessage() {}

func (x *StreamSceneChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneChangesRequest.ProtoReflect.Descriptor instead.
func (*StreamSceneChangesRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{20}
}

type StreamSceneChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneMetadata *SceneMetadata         `protobuf:"bytes,1,opt,name=scene_metadata,json=sceneMetadata,proto3" json:"scene_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSceneChangesResponse) Reset() {
	*x = StreamSceneChangesResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSceneChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSceneChangesResponse) ProtoMessage() {}

func (x *StreamSceneChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSceneChangesResponse.ProtoReflect.Descriptor instead.
func (*StreamSceneChangesResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *StreamSceneChangesResponse) GetSceneMetadata() *SceneMetadata {
	if x != nil {
		return x.SceneMetadata
	}
	return nil
}

type RemoveAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllRequest) Reset() {
	*x = RemoveAllRequest{}
	mi := &file_draw_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllRequest) ProtoMessage() {}

func (x *RemoveAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllRequest) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{22}
}

type RemoveAllResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransformCount int32                  `protobuf:"varint,1,opt,name=transform_count,json=transformCount,proto3" json:"transform_count,omitempty"`
	DrawingCount   int32                  `protobuf:"varint,2,opt,name=drawing_count,json=drawingCount,proto3" json:"drawing_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveAllResponse) Reset() {
	*x = RemoveAllResponse{}
	mi := &file_draw_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllResponse) ProtoMessage() {}

func (x *RemoveAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllResponse) Descriptor() ([]byte, []int) {
	return file_draw_v1_service_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveAllResponse) GetTransformCount() int32 {
	if x != nil {
		return x.TransformCount
	}
	return 0
}

func (x *RemoveAllResponse) GetDrawingCount() int32 {
	if x != nil {
		return x.DrawingCount
	}
	return 0
}

var File_draw_v1_service_proto protoreflect.FileDescriptor

const file_draw_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15draw/v1/service.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\x1a\x15draw/v1/drawing.proto\x1a\x13draw/v1/scene.proto\"N\n" +
	"\x13AddTransformRequest\x127\n" +
	"\ttransform\x18\x01 \x01(\v2\x19.viam.common.v1.TransformR\ttransform\"*\n" +
	"\x14AddTransformResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"e\n" +
	"\x16UpdateTransformRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x127\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformR\ttransform\"\x19\n" +
	"\x17UpdateTransformResponse\",\n" +
	"\x16RemoveTransformRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x19\n" +
	"\x17RemoveTransformResponse\"\x1c\n" +
	"\x1aRemoveAllTransformsRequest\"3\n" +
	"\x1bRemoveAllTransformsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x1f\n" +
	"\x1dStreamTransformChangesRequest\"\x8f\x01\n" +
	"\x1eStreamTransformChangesResponse\x124\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x13.draw.v1.ChangeTypeR\n" +
	"changeType\x127\n" +
	"\ttransform\x18\x02 \x01(\v2\x19.viam.common.v1.TransformR\ttransform\"?\n" +
	"\x11AddDrawingRequest\x12*\n" +
	"\adrawing\x18\x01 \x01(\v2\x10.draw.v1.DrawingR\adrawing\"(\n" +
	"\x12AddDrawingResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"V\n" +
	"\x14UpdateDrawingRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12*\n" +
	"\adrawing\x18\x02 \x01(\v2\x10.draw.v1.DrawingR\adrawing\"\x17\n" +
	"\x15UpdateDrawingResponse\"*\n" +
	"\x14RemoveDrawingRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"\x17\n" +
	"\x15RemoveDrawingResponse\"\x1a\n" +
	"\x18RemoveAllDrawingsRequest\"1\n" +
	"\x19RemoveAllDrawingsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x1d\n" +
	"\x1bStreamDrawingChangesRequest\"\x80\x01\n" +
	"\x1cStreamDrawingChangesResponse\x124\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x13.draw.v1.ChangeTypeR\n" +
	"changeType\x12*\n" +
	"\adrawing\x18\x02 \x01(\v2\x10.draw.v1.DrawingR\adrawing\"\x1b\n" +
	"\x19StreamSceneChangesRequest\"[\n" +
	"\x1aStreamSceneChangesResponse\x12=\n" +
	"\x0escene_metadata\x18\x01 \x01(\v2\x16.draw.v1.SceneMetadataR\rsceneMetadata\"\x12\n" +
	"\x10RemoveAllRequest\"a\n" +
	"\x11RemoveAllResponse\x12'\n" +
	"\x0ftransform_count\x18\x01 \x01(\x05R\x0etransformCount\x12#\n" +
	"\rdrawing_count\x18\x02 \x01(\x05R\fdrawingCount*r\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CHANGE_TYPE_ADDED\x10\x01\x12\x17\n" +
	"\x13CHANGE_TYPE_REMOVED\x10\x02\x12\x17\n" +
	"\x13CHANGE_TYPE_UPDATED\x10\x032\xa4\b\n" +
	"\vDrawService\x12K\n" +
	"\fAddTransform\x12\x1c.draw.v1.AddTransformRequest\x1a\x1d.draw.v1.AddTransformResponse\x12T\n" +
	"\x0fUpdateTransform\x12\x1f.draw.v1.UpdateTransformRequest\x1a .draw.v1.UpdateTransformResponse\x12T\n" +
	"\x0fRemoveTransform\x12\x1f.draw.v1.RemoveTransformRequest\x1a .draw.v1.RemoveTransformResponse\x12`\n" +
	"\x13RemoveAllTransforms\x12#.draw.v1.RemoveAllTransformsRequest\x1a$.draw.v1.RemoveAllTransformsResponse\x12k\n" +
	"\x16StreamTransformChanges\x12&.draw.v1.StreamTransformChangesRequest\x1a'.draw.v1.StreamTransformChangesResponse0\x01\x12E\n" +
	"\n" +
	"AddDrawing\x12\x1a.draw.v1.AddDrawingRequest\x1a\x1b.draw.v1.AddDrawingResponse\x12N\n" +
	"\rUpdateDrawing\x12\x1d.draw.v1.UpdateDrawingRequest\x1a\x1e.draw.v1.UpdateDrawingResponse\x12N\n" +
	"\rRemoveDrawing\x12\x1d.draw.v1.RemoveDrawingRequest\x1a\x1e.draw.v1.RemoveDrawingResponse\x12Z\n" +
	"\x11RemoveAllDrawings\x12!.draw.v1.RemoveAllDrawingsRequest\x1a\".draw.v1.RemoveAllDrawingsResponse\x12e\n" +
	"\x14StreamDrawingChanges\x12$.draw.v1.StreamDrawingChangesRequest\x1a%.draw.v1.StreamDrawingChangesResponse0\x01\x12_\n" +
	"\x12StreamSceneChanges\x12\".draw.v1.StreamSceneChangesRequest\x1a#.draw.v1.StreamSceneChangesResponse0\x01\x12B\n" +
	"\tRemoveAll\x12\x19.draw.v1.RemoveAllRequest\x1a\x1a.draw.v1.RemoveAllResponseB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_service_proto_rawDescOnce sync.Once
	file_draw_v1_service_proto_rawDescData []byte
)

func file_draw_v1_service_proto_rawDescGZIP() []byte {
	file_draw_v1_service_proto_rawDescOnce.Do(func() {
		file_draw_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)))
	})
	return file_draw_v1_service_proto_rawDescData
}

var file_draw_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_draw_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_draw_v1_service_proto_goTypes = []any{
	(ChangeType)(0),                        // 0: draw.v1.ChangeType
	(*AddTransformRequest)(nil),            // 1: draw.v1.AddTransformRequest
	(*AddTransformResponse)(nil),           // 2: draw.v1.AddTransformResponse
	(*UpdateTransformRequest)(nil),         // 3: draw.v1.UpdateTransformRequest
	(*UpdateTransformResponse)(nil),        // 4: draw.v1.UpdateTransformResponse
	(*RemoveTransformRequest)(nil),         // 5: draw.v1.RemoveTransformRequest
	(*RemoveTransformResponse)(nil),        // 6: draw.v1.RemoveTransformResponse
	(*RemoveAllTransformsRequest)(nil),     // 7: draw.v1.RemoveAllTransformsRequest
	(*RemoveAllTransformsResponse)(nil),    // 8: draw.v1.RemoveAllTransformsResponse
	(*StreamTransformChangesRequest)(nil),  // 9: draw.v1.StreamTransformChangesRequest
	(*StreamTransformChangesResponse)(nil), // 10: draw.v1.StreamTransformChangesResponse
	(*AddDrawingRequest)(nil),              // 11: draw.v1.AddDrawingRequest
	(*AddDrawingResponse)(nil),             // 12: draw.v1.AddDrawingResponse
	(*UpdateDrawingRequest)(nil),           // 13: draw.v1.UpdateDrawingRequest
	(*UpdateDrawingResponse)(nil),          // 14: draw.v1.UpdateDrawingResponse
	(*RemoveDrawingRequest)(nil),           // 15: draw.v1.RemoveDrawingRequest
	(*RemoveDrawingResponse)(nil),          // 16: draw.v1.RemoveDrawingResponse
	(*RemoveAllDrawingsRequest)(nil),       // 17: draw.v1.RemoveAllDrawingsRequest
	(*RemoveAllDrawingsResponse)(nil),      // 18: draw.v1.RemoveAllDrawingsResponse
	(*StreamDrawingChangesRequest)(nil),    // 19: draw.v1.StreamDrawingChangesRequest
	(*StreamDrawingChangesResponse)(nil),   // 20: draw.v1.StreamDrawingChangesResponse
	(*StreamSceneChangesRequest)(nil),      // 21: draw.v1.StreamSceneChangesRequest
	(*StreamSceneChangesResponse)(nil),     // 22: draw.v1.StreamSceneChangesResponse
	(*RemoveAllRequest)(nil),               // 23: draw.v1.RemoveAllRequest
	(*RemoveAllResponse)(nil),              // 24: draw.v1.RemoveAllResponse
	(*v1.Transform)(nil),                   // 25: viam.common.v1.Transform
	(*Drawing)(nil),                        // 26: draw.v1.Drawing
	(*SceneMetadata)(nil),                  // 27: draw.v1.SceneMetadata
}
var file_draw_v1_service_proto_depIdxs = []int32{
	25, // 0: draw.v1.AddTransformRequest.transform:type_name -> viam.common.v1.Transform
	25, // 1: draw.v1.UpdateTransformRequest.transform:type_name -> viam.common.v1.Transform
	0,  // 2: draw.v1.StreamTransformChangesResponse.change_type:type_name -> draw.v1.ChangeType
	25, // 3: draw.v1.StreamTransformChangesResponse.transform:type_name -> viam.common.v1.Transform
	26, // 4: draw.v1.AddDrawingRequest.drawing:type_name -> draw.v1.Drawing
	26, // 5: draw.v1.UpdateDrawingRequest.drawing:type_name -> draw.v1.Drawing
	0,  // 6: draw.v1.StreamDrawingChangesResponse.change_type:type_name -> draw.v1.ChangeType
	26, // 7: draw.v1.StreamDrawingChangesResponse.drawing:type_name -> draw.v1.Drawing
	27, // 8: draw.v1.StreamSceneChangesResponse.scene_metadata:type_name -> draw.v1.SceneMetadata
	1,  // 9: draw.v1.DrawService.AddTransform:input_type -> draw.v1.AddTransformRequest
	3,  // 10: draw.v1.DrawService.UpdateTransform:input_type -> draw.v1.UpdateTransformRequest
	5,  // 11: draw.v1.DrawService.RemoveTransform:input_type -> draw.v1.RemoveTransformRequest
	7,  // 12: draw.v1.DrawService.RemoveAllTransforms:input_type -> draw.v1.RemoveAllTransformsRequest
	9,  // 13: draw.v1.DrawService.StreamTransformChanges:input_type -> draw.v1.StreamTransformChangesRequest
	11, // 14: draw.v1.DrawService.AddDrawing:input_type -> draw.v1.AddDrawingRequest
	13, // 15: draw.v1.DrawService.UpdateDrawing:input_type -> draw.v1.UpdateDrawingRequest
	15, // 16: draw.v1.DrawService.RemoveDrawing:input_type -> draw.v1.RemoveDrawingRequest
	17, // 17: draw.v1.DrawService.RemoveAllDrawings:input_type -> draw.v1.RemoveAllDrawingsRequest
	19, // 18: draw.v1.DrawService.StreamDrawingChanges:input_type -> draw.v1.StreamDrawingChangesRequest
	21, // 19: draw.v1.DrawService.StreamSceneChanges:input_type -> draw.v1.StreamSceneChangesRequest
	23, // 20: draw.v1.DrawService.RemoveAll:input_type -> draw.v1.RemoveAllRequest
	2,  // 21: draw.v1.DrawService.AddTransform:output_type -> draw.v1.AddTransformResponse
	4,  // 22: draw.v1.DrawService.UpdateTransform:output_type -> draw.v1.UpdateTransformResponse
	6,  // 23: draw.v1.DrawService.RemoveTransform:output_type -> draw.v1.RemoveTransformResponse
	8,  // 24: draw.v1.DrawService.RemoveAllTransforms:output_type -> draw.v1.RemoveAllTransformsResponse
	10, // 25: draw.v1.DrawService.StreamTransformChanges:output_type -> draw.v1.StreamTransformChangesResponse
	12, // 26: draw.v1.DrawService.AddDrawing:output_type -> draw.v1.AddDrawingResponse
	14, // 27: draw.v1.DrawService.UpdateDrawing:output_type -> draw.v1.UpdateDrawingResponse
	16, // 28: draw.v1.DrawService.RemoveDrawing:output_type -> draw.v1.RemoveDrawingResponse
	18, // 29: draw.v1.DrawService.RemoveAllDrawings:output_type -> draw.v1.RemoveAllDrawingsResponse
	20, // 30: draw.v1.DrawService.StreamDrawingChanges:output_type -> draw.v1.StreamDrawingChangesResponse
	22, // 31: draw.v1.DrawService.StreamSceneChanges:output_type -> draw.v1.StreamSceneChangesResponse
	24, // 32: draw.v1.DrawService.RemoveAll:output_type -> draw.v1.RemoveAllResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_draw_v1_service_proto_init() }
func file_draw_v1_service_proto_init() {
	if File_draw_v1_service_proto != nil {
		return
	}
	file_draw_v1_drawing_proto_init()
	file_draw_v1_scene_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_service_proto_rawDesc), len(file_draw_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_draw_v1_service_proto_goTypes,
		DependencyIndexes: file_draw_v1_service_proto_depIdxs,
		EnumInfos:         file_draw_v1_service_proto_enumTypes,
		MessageInfos:      file_draw_v1_service_proto_msgTypes,
	}.Build()
	File_draw_v1_service_proto = out.File
	file_draw_v1_service_proto_goTypes = nil
	file_draw_v1_service_proto_depIdxs = nil
}
