// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/snapshot.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the list of transforms and shapes in the scene to render
	Transforms []*v1.Transform `protobuf:"bytes,1,rep,name=transforms,proto3" json:"transforms,omitempty"`
	// the list of drawings in the scene to render
	Drawings []*Drawing `protobuf:"bytes,2,rep,name=drawings,proto3" json:"drawings,omitempty"`
	// a unique ID for the snapshot, to inform the visualizer if a new snapshot is being rendered
	Uuid []byte `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// optional metadata for the scene, matches the visualizer's "settings"
	SceneMetadata *SceneMetadata `protobuf:"bytes,4,opt,name=scene_metadata,json=sceneMetadata,proto3,oneof" json:"scene_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_draw_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_draw_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetTransforms() []*v1.Transform {
	if x != nil {
		return x.Transforms
	}
	return nil
}

func (x *Snapshot) GetDrawings() []*Drawing {
	if x != nil {
		return x.Drawings
	}
	return nil
}

func (x *Snapshot) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Snapshot) GetSceneMetadata() *SceneMetadata {
	if x != nil {
		return x.SceneMetadata
	}
	return nil
}

var File_draw_v1_snapshot_proto protoreflect.FileDescriptor

const file_draw_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x16draw/v1/snapshot.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\x1a\x15draw/v1/drawing.proto\x1a\x13draw/v1/scene.proto\"\xde\x01\n" +
	"\bSnapshot\x129\n" +
	"\n" +
	"transforms\x18\x01 \x03(\v2\x19.viam.common.v1.TransformR\n" +
	"transforms\x12,\n" +
	"\bdrawings\x18\x02 \x03(\v2\x10.draw.v1.DrawingR\bdrawings\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\fR\x04uuid\x12B\n" +
	"\x0escene_metadata\x18\x04 \x01(\v2\x16.draw.v1.SceneMetadataH\x00R\rsceneMetadata\x88\x01\x01B\x11\n" +
	"\x0f_scene_metadataB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_snapshot_proto_rawDescOnce sync.Once
	file_draw_v1_snapshot_proto_rawDescData []byte
)

func file_draw_v1_snapshot_proto_rawDescGZIP() []byte {
	file_draw_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_draw_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_snapshot_proto_rawDesc), len(file_draw_v1_snapshot_proto_rawDesc)))
	})
	return file_draw_v1_snapshot_proto_rawDescData
}

var file_draw_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_draw_v1_snapshot_proto_goTypes = []any{
	(*Snapshot)(nil),      // 0: draw.v1.Snapshot
	(*v1.Transform)(nil),  // 1: viam.common.v1.Transform
	(*Drawing)(nil),       // 2: draw.v1.Drawing
	(*SceneMetadata)(nil), // 3: draw.v1.SceneMetadata
}
var file_draw_v1_snapshot_proto_depIdxs = []int32{
	1, // 0: draw.v1.Snapshot.transforms:type_name -> viam.common.v1.Transform
	2, // 1: draw.v1.Snapshot.drawings:type_name -> draw.v1.Drawing
	3, // 2: draw.v1.Snapshot.scene_metadata:type_name -> draw.v1.SceneMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_draw_v1_snapshot_proto_init() }
func file_draw_v1_snapshot_proto_init() {
	if File_draw_v1_snapshot_proto != nil {
		return
	}
	file_draw_v1_drawing_proto_init()
	file_draw_v1_scene_proto_init()
	file_draw_v1_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_snapshot_proto_rawDesc), len(file_draw_v1_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_draw_v1_snapshot_proto_depIdxs,
		MessageInfos:      file_draw_v1_snapshot_proto_msgTypes,
	}.Build()
	File_draw_v1_snapshot_proto = out.File
	file_draw_v1_snapshot_proto_goTypes = nil
	file_draw_v1_snapshot_proto_depIdxs = nil
}
