// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/transforms.proto

package drawv1

import (
	v1 "go.viam.com/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transforms is a list of transforms
// TODO: Here for backwards compatibility for the draw API, remove in a future release
type Transforms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transforms    []*v1.Transform        `protobuf:"bytes,1,rep,name=transforms,proto3" json:"transforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transforms) Reset() {
	*x = Transforms{}
	mi := &file_draw_v1_transforms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transforms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transforms) ProtoMessage() {}

func (x *Transforms) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_transforms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transforms.ProtoReflect.Descriptor instead.
func (*Transforms) Descriptor() ([]byte, []int) {
	return file_draw_v1_transforms_proto_rawDescGZIP(), []int{0}
}

func (x *Transforms) GetTransforms() []*v1.Transform {
	if x != nil {
		return x.Transforms
	}
	return nil
}

var File_draw_v1_transforms_proto protoreflect.FileDescriptor

const file_draw_v1_transforms_proto_rawDesc = "" +
	"\n" +
	"\x18draw/v1/transforms.proto\x12\adraw.v1\x1a\x16common/v1/common.proto\"G\n" +
	"\n" +
	"Transforms\x129\n" +
	"\n" +
	"transforms\x18\x01 \x03(\v2\x19.viam.common.v1.TransformR\n" +
	"transformsB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_transforms_proto_rawDescOnce sync.Once
	file_draw_v1_transforms_proto_rawDescData []byte
)

func file_draw_v1_transforms_proto_rawDescGZIP() []byte {
	file_draw_v1_transforms_proto_rawDescOnce.Do(func() {
		file_draw_v1_transforms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_transforms_proto_rawDesc), len(file_draw_v1_transforms_proto_rawDesc)))
	})
	return file_draw_v1_transforms_proto_rawDescData
}

var file_draw_v1_transforms_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_draw_v1_transforms_proto_goTypes = []any{
	(*Transforms)(nil),   // 0: draw.v1.Transforms
	(*v1.Transform)(nil), // 1: viam.common.v1.Transform
}
var file_draw_v1_transforms_proto_depIdxs = []int32{
	1, // 0: draw.v1.Transforms.transforms:type_name -> viam.common.v1.Transform
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_draw_v1_transforms_proto_init() }
func file_draw_v1_transforms_proto_init() {
	if File_draw_v1_transforms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_transforms_proto_rawDesc), len(file_draw_v1_transforms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_transforms_proto_goTypes,
		DependencyIndexes: file_draw_v1_transforms_proto_depIdxs,
		MessageInfos:      file_draw_v1_transforms_proto_msgTypes,
	}.Build()
	File_draw_v1_transforms_proto = out.File
	file_draw_v1_transforms_proto_goTypes = nil
	file_draw_v1_transforms_proto_depIdxs = nil
}
