import { build } from 'esbuild'
import { writeFileSync } from 'node:fs'

const workerPaths = ['src/lib/loaders/pcd/worker.ts']

for (const workerPath of workerPaths) {
	const result = await build({
		entryPoints: [workerPath],
		bundle: true,
		format: 'iife',
		write: false,
		minify: true,
	})

	const code = result.outputFiles[0].text
	const escaped = code
		.replaceAll('\\', '\\\\')
		.replaceAll('`', '\\`')
		.replaceAll('$', String.raw`\$`)
	const outFile = `${workerPath.replace('.ts', '.inline.ts')}`

	writeFileSync(
		outFile,
		`// AUTO-GENERATED by scripts/build-workers.js - do not edit\nexport const workerCode = \`${escaped}\`\n`
	)

	console.log(`Built ${workerPath} into ${outFile}`)
}

console.log('Built all workers')
