import { execSync } from 'child_process'
import { readFileSync, writeFileSync } from 'fs'

const outFile = 'scripts/.worker-bundle-tmp.js'

// pcd loader worker
execSync(
	`node_modules/.bin/esbuild src/lib/loaders/pcd/worker.ts --bundle --format=iife --minify --outfile=${outFile}`,
	{ stdio: 'inherit' }
)

const code = readFileSync(outFile, 'utf8')
const escaped = code.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

writeFileSync(
	'src/lib/loaders/pcd/worker.inline.ts',
	`// AUTO-GENERATED by scripts/build-worker.mjs - do not edit\nexport const workerCode = \`${escaped}\`\n`
)

// clean up temp bundle
execSync(`rm ${outFile}`)

console.log('Built worker.inline.ts')
